language: php
#sudo: false
#dist: trusty

cache:
    directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

addons:
  apt:
    packages:
    - libxml2-dev
#    - libsodium-dev

env:
  matrix:
    -

matrix:
  include:
    - php: 7.2
      env:
        - PHPCS=1
    - php: 7.3
      env:
        - PHPCS=1
  allow_failures:
    - php: 7.2
      env:
        - PHPCS=1
    - php: 7.3
      env:
        - PHPCS=1

before_install:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
#  - pecl install libsodium
#  - echo "extension = sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#  - php -i
  - echo "Travis PHP Version: $TRAVIS_PHP_VERSION"
  - echo "${TRAVIS_PHP_VERSION:0:4}"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:4} == '7.2.' ]] ; then
      pecl install libsodium;
    fi;

install:
#  - pecl install libsodium
  - REMOVE_PACKAGE="squizlabs/php_codesniffer"; if [ "$PHPCS" = 1 ]; then REMOVE_PACKAGE="phpunit/phpunit"; fi; composer remove --no-update --no-scripts --dev $REMOVE_PACKAGE
  - travis_retry composer install --prefer-dist
  - phpenv rehash

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS quickbooks_tests;'
  - psql -U postgres -c 'CREATE DATABASE quickbooks_tests;'
  - cat tests/database-configuration.ini-example | sed 's/^;enabled/enabled/' | sed 's/^username = "mysql"/username = "travis"/' > tests/database-configuration.ini

script:
  - if [[ "$PHPCS" == 1 ]]; then vendor/bin/phpcs --standard=psr12 src/ tests/; exit $?; fi;
  - vendor/bin/phpunit --bootstrap vendor/autoload.php --coverage-text --whitelist src/QuickBooksPhpDevKit --verbose tests/

services:
  - mysql
  - postgresql
  
notifications:
  email: false
