<?php declare(strict_types=1);

/**
 * Schema object for: BillToPayQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class BillToPayQueryRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'PayeeEntityRef ListID' => 'IDTYPE',
		'PayeeEntityRef FullName' => 'STRTYPE',
		'APAccountRef ListID' => 'IDTYPE',
		'APAccountRef FullName' => 'STRTYPE',
		'DueDate' => 'DATETYPE',
		'CurrencyFilter ListID' => 'IDTYPE',
		'CurrencyFilter FullName' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'PayeeEntityRef FullName' => 209,
		'APAccountRef FullName' => 209,
		'CurrencyFilter FullName' => 209,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'PayeeEntityRef',
		'PayeeEntityRef ListID',
		'PayeeEntityRef FullName',
		'APAccountRef',
		'APAccountRef ListID',
		'APAccountRef FullName',
		'DueDate',
		'CurrencyFilter',
		'CurrencyFilter ListID',
		'CurrencyFilter FullName',
		'IncludeRetElement',
	];
}
