<?php declare(strict_types=1);

/**
 * Schema object for: BillPaymentCreditCardAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class BillPaymentCreditCardAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'BillPaymentCreditCardAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'PayeeEntityRef ListID' => 'IDTYPE',
		'PayeeEntityRef FullName' => 'STRTYPE',
		'APAccountRef ListID' => 'IDTYPE',
		'APAccountRef FullName' => 'STRTYPE',
		'TxnDate' => 'DATETYPE',
		'CreditCardAccountRef ListID' => 'IDTYPE',
		'CreditCardAccountRef FullName' => 'STRTYPE',
		'RefNumber' => 'STRTYPE',
		'Memo' => 'STRTYPE',
		'ExchangeRate' => 'FLOATTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'AppliedToTxnAdd TxnID' => 'IDTYPE',
		'AppliedToTxnAdd PaymentAmount' => 'AMTTYPE',
		'AppliedToTxnAdd TxnLineDetail TxnLineID' => 'IDTYPE',
		'AppliedToTxnAdd TxnLineDetail Amount' => 'AMTTYPE',
		'AppliedToTxnAdd SetCredit CreditTxnID' => 'IDTYPE',
		'AppliedToTxnAdd SetCredit TxnLineID' => 'IDTYPE',
		'AppliedToTxnAdd SetCredit AppliedAmount' => 'AMTTYPE',
		'AppliedToTxnAdd SetCredit Override' => 'BOOLTYPE',
		'AppliedToTxnAdd DiscountAmount' => 'AMTTYPE',
		'AppliedToTxnAdd DiscountAccountRef ListID' => 'IDTYPE',
		'AppliedToTxnAdd DiscountAccountRef FullName' => 'STRTYPE',
		'AppliedToTxnAdd DiscountClassRef ListID' => 'IDTYPE',
		'AppliedToTxnAdd DiscountClassRef FullName' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'PayeeEntityRef FullName' => 209,
		'APAccountRef FullName' => 159,
		'CreditCardAccountRef FullName' => 159,
		'RefNumber' => 11,
		'Memo' => 4095,
		'AppliedToTxnAdd DiscountAccountRef FullName' => 159,
		'AppliedToTxnAdd DiscountClassRef FullName' => 159,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'Memo' => 3.0,
		'ExchangeRate' => 8.0,
		'ExternalGUID' => 9.0,
		'AppliedToTxnAdd SetCredit Override' => 10.0,
		'AppliedToTxnAdd DiscountClassRef ListID' => 11.0,
		'AppliedToTxnAdd DiscountClassRef FullName' => 11.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'AppliedToTxnAdd TxnLineDetail TxnLineID' => ['US','CA','UK','AU'],
		'AppliedToTxnAdd TxnLineDetail Amount' => ['US','CA','UK','AU'],
		'AppliedToTxnAdd SetCredit TxnLineID' => ['US','CA','UK','AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'PayeeEntityRef',
		'PayeeEntityRef ListID',
		'PayeeEntityRef FullName',
		'APAccountRef',
		'APAccountRef ListID',
		'APAccountRef FullName',
		'TxnDate',
		'CreditCardAccountRef',
		'CreditCardAccountRef ListID',
		'CreditCardAccountRef FullName',
		'RefNumber',
		'Memo',
		'ExchangeRate',
		'ExternalGUID',
		'AppliedToTxnAdd',
		'AppliedToTxnAdd TxnID',
		'AppliedToTxnAdd PaymentAmount',
		'AppliedToTxnAdd TxnLineDetail TxnLineID',
		'AppliedToTxnAdd TxnLineDetail Amount',
		'AppliedToTxnAdd SetCredit CreditTxnID',
		'AppliedToTxnAdd SetCredit TxnLineID',
		'AppliedToTxnAdd SetCredit AppliedAmount',
		'AppliedToTxnAdd SetCredit Override',
		'AppliedToTxnAdd DiscountAmount',
		'AppliedToTxnAdd DiscountAccountRef ListID',
		'AppliedToTxnAdd DiscountAccountRef FullName',
		'AppliedToTxnAdd DiscountClassRef ListID',
		'AppliedToTxnAdd DiscountClassRef FullName',
		'IncludeRetElement',
	];
}
