<?php declare(strict_types=1);

/**
 * Schema object for: BuildAssemblyQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class BuildAssemblyQueryRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'TxnID' => 'IDTYPE',
			'RefNumber' => 'STRTYPE',
			'RefNumberCaseSensitive' => 'STRTYPE',
			'MaxReturned' => 'INTTYPE',
			'ModifiedDateRangeFilter FromModifiedDate' => 'DATETIMETYPE',
			'ModifiedDateRangeFilter ToModifiedDate' => 'DATETIMETYPE',
			'TxnDateRangeFilter FromTxnDate' => 'DATETYPE',
			'TxnDateRangeFilter ToTxnDate' => 'DATETYPE',
			'TxnDateRangeFilter DateMacro' => 'ENUMTYPE',
			'ItemFilter ListID' => 'IDTYPE',
			'ItemFilter FullName' => 'STRTYPE',
			'ItemFilter ListIDWithChildren' => 'IDTYPE',
			'ItemFilter FullNameWithChildren' => 'STRTYPE',
			'RefNumberFilter MatchCriterion' => 'ENUMTYPE',
			'RefNumberFilter RefNumber' => 'STRTYPE',
			'RefNumberRangeFilter FromRefNumber' => 'STRTYPE',
			'RefNumberRangeFilter ToRefNumber' => 'STRTYPE',
			'PendingStatus' => 'ENUMTYPE',
			'IncludeComponentLineItems' => 'BOOLTYPE',
			'IncludeRetElement' => 'STRTYPE',
			'OwnerID' => 'GUIDTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'TxnID' => 0,
			'RefNumber' => 0,
			'RefNumberCaseSensitive' => 0,
			'MaxReturned' => 0,
			'ModifiedDateRangeFilter FromModifiedDate' => 0,
			'ModifiedDateRangeFilter ToModifiedDate' => 0,
			'TxnDateRangeFilter FromTxnDate' => 0,
			'TxnDateRangeFilter ToTxnDate' => 0,
			'TxnDateRangeFilter DateMacro' => 0,
			'ItemFilter ListID' => 0,
			'ItemFilter FullName' => 159,
			'ItemFilter ListIDWithChildren' => 0,
			'ItemFilter FullNameWithChildren' => 159,
			'RefNumberFilter MatchCriterion' => 0,
			'RefNumberFilter RefNumber' => 0,
			'RefNumberRangeFilter FromRefNumber' => 0,
			'RefNumberRangeFilter ToRefNumber' => 0,
			'PendingStatus' => 0,
			'IncludeComponentLineItems' => 0,
			'IncludeRetElement' => 50,
			'OwnerID' => 0,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'TxnID' => 999.99,
			'RefNumber' => 999.99,
			'RefNumberCaseSensitive' => 999.99,
			'MaxReturned' => 999.99,
			'ModifiedDateRangeFilter FromModifiedDate' => 999.99,
			'ModifiedDateRangeFilter ToModifiedDate' => 999.99,
			'TxnDateRangeFilter FromTxnDate' => 999.99,
			'TxnDateRangeFilter ToTxnDate' => 999.99,
			'TxnDateRangeFilter DateMacro' => 999.99,
			'ItemFilter ListID' => 999.99,
			'ItemFilter FullName' => 999.99,
			'ItemFilter ListIDWithChildren' => 999.99,
			'ItemFilter FullNameWithChildren' => 999.99,
			'RefNumberFilter MatchCriterion' => 999.99,
			'RefNumberFilter RefNumber' => 999.99,
			'RefNumberRangeFilter FromRefNumber' => 999.99,
			'RefNumberRangeFilter ToRefNumber' => 999.99,
			'PendingStatus' => 999.99,
			'IncludeComponentLineItems' => 999.99,
			'IncludeRetElement' => 999.99,
			'OwnerID' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'TxnID' => true,
			'RefNumber' => true,
			'RefNumberCaseSensitive' => true,
			'MaxReturned' => false,
			'ModifiedDateRangeFilter FromModifiedDate' => false,
			'ModifiedDateRangeFilter ToModifiedDate' => false,
			'TxnDateRangeFilter FromTxnDate' => false,
			'TxnDateRangeFilter ToTxnDate' => false,
			'TxnDateRangeFilter DateMacro' => false,
			'ItemFilter ListID' => true,
			'ItemFilter FullName' => true,
			'ItemFilter ListIDWithChildren' => false,
			'ItemFilter FullNameWithChildren' => false,
			'RefNumberFilter MatchCriterion' => false,
			'RefNumberFilter RefNumber' => true,
			'RefNumberRangeFilter FromRefNumber' => false,
			'RefNumberRangeFilter ToRefNumber' => false,
			'PendingStatus' => false,
			'IncludeComponentLineItems' => false,
			'IncludeRetElement' => true,
			'OwnerID' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'TxnID',
			'RefNumber',
			'RefNumberCaseSensitive',
			'MaxReturned',
			'ModifiedDateRangeFilter',
			'ModifiedDateRangeFilter FromModifiedDate',
			'ModifiedDateRangeFilter ToModifiedDate',
			'TxnDateRangeFilter',
			'TxnDateRangeFilter FromTxnDate',
			'TxnDateRangeFilter ToTxnDate',
			'TxnDateRangeFilter DateMacro',
			'ItemFilter',
			'ItemFilter ListID',
			'ItemFilter FullName',
			'ItemFilter ListIDWithChildren',
			'ItemFilter FullNameWithChildren',
			'RefNumberFilter',
			'RefNumberFilter MatchCriterion',
			'RefNumberFilter RefNumber',
			'RefNumberRangeFilter',
			'RefNumberRangeFilter FromRefNumber',
			'RefNumberRangeFilter ToRefNumber',
			'PendingStatus',
			'IncludeComponentLineItems',
			'IncludeRetElement',
			'OwnerID',
		];

		return $paths;
	}
}
