<?php declare(strict_types=1);

/**
 * Schema object for: BuildAssemblyQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class BuildAssemblyQueryRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TxnID' => 'IDTYPE',
		'RefNumber' => 'STRTYPE',
		'RefNumberCaseSensitive' => 'STRTYPE',
		'MaxReturned' => 'INTTYPE',
		'ModifiedDateRangeFilter FromModifiedDate' => 'DATETIMETYPE',
		'ModifiedDateRangeFilter ToModifiedDate' => 'DATETIMETYPE',
		'TxnDateRangeFilter FromTxnDate' => 'DATETYPE',
		'TxnDateRangeFilter ToTxnDate' => 'DATETYPE',
		'TxnDateRangeFilter DateMacro' => 'ENUMTYPE',
		'ItemFilter ListID' => 'IDTYPE',
		'ItemFilter FullName' => 'STRTYPE',
		'ItemFilter ListIDWithChildren' => 'IDTYPE',
		'ItemFilter FullNameWithChildren' => 'STRTYPE',
		'RefNumberFilter MatchCriterion' => 'ENUMTYPE',
		'RefNumberFilter RefNumber' => 'STRTYPE',
		'RefNumberRangeFilter FromRefNumber' => 'STRTYPE',
		'RefNumberRangeFilter ToRefNumber' => 'STRTYPE',
		'PendingStatus' => 'ENUMTYPE',
		'IncludeComponentLineItems' => 'BOOLTYPE',
		'IncludeRetElement' => 'STRTYPE',
		'OwnerID' => 'GUIDTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'ItemFilter FullName' => 159,
		'ItemFilter FullNameWithChildren' => 159,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'TxnID' => true,
		'RefNumber' => true,
		'RefNumberCaseSensitive' => true,
		'ItemFilter ListID' => true,
		'ItemFilter FullName' => true,
		'RefNumberFilter RefNumber' => true,
		'IncludeRetElement' => true,
		'OwnerID' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TxnID',
		'RefNumber',
		'RefNumberCaseSensitive',
		'MaxReturned',
		'ModifiedDateRangeFilter',
		'ModifiedDateRangeFilter FromModifiedDate',
		'ModifiedDateRangeFilter ToModifiedDate',
		'TxnDateRangeFilter',
		'TxnDateRangeFilter FromTxnDate',
		'TxnDateRangeFilter ToTxnDate',
		'TxnDateRangeFilter DateMacro',
		'ItemFilter',
		'ItemFilter ListID',
		'ItemFilter FullName',
		'ItemFilter ListIDWithChildren',
		'ItemFilter FullNameWithChildren',
		'RefNumberFilter',
		'RefNumberFilter MatchCriterion',
		'RefNumberFilter RefNumber',
		'RefNumberRangeFilter',
		'RefNumberRangeFilter FromRefNumber',
		'RefNumberRangeFilter ToRefNumber',
		'PendingStatus',
		'IncludeComponentLineItems',
		'IncludeRetElement',
		'OwnerID',
	];
}
