<?php declare(strict_types=1);

/**
 * Schema object for: BuildAssemblyAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class BuildAssemblyAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'BuildAssemblyAdd ItemInventoryAssemblyRef ListID' => 'IDTYPE',
			'BuildAssemblyAdd ItemInventoryAssemblyRef FullName' => 'STRTYPE',
			'BuildAssemblyAdd InventorySiteRef ListID' => 'IDTYPE',
			'BuildAssemblyAdd InventorySiteRef FullName' => 'STRTYPE',
			'BuildAssemblyAdd InventorySiteLocationRef ListID' => 'IDTYPE',
			'BuildAssemblyAdd InventorySiteLocationRef FullName' => 'STRTYPE',
			'BuildAssemblyAdd SerialNumber' => 'STRTYPE',
			'BuildAssemblyAdd LotNumber' => 'STRTYPE',
			'BuildAssemblyAdd TxnDate' => 'DATETYPE',
			'BuildAssemblyAdd RefNumber' => 'STRTYPE',
			'BuildAssemblyAdd Memo' => 'STRTYPE',
			'BuildAssemblyAdd QuantityToBuild' => 'QUANTYPE',
			'BuildAssemblyAdd MarkPendingIfRequired' => 'BOOLTYPE',
			'BuildAssemblyAdd ExternalGUID' => 'GUIDTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'BuildAssemblyAdd ItemInventoryAssemblyRef ListID' => 0,
			'BuildAssemblyAdd ItemInventoryAssemblyRef FullName' => 159,
			'BuildAssemblyAdd InventorySiteRef ListID' => 0,
			'BuildAssemblyAdd InventorySiteRef FullName' => 159,
			'BuildAssemblyAdd InventorySiteLocationRef ListID' => 0,
			'BuildAssemblyAdd InventorySiteLocationRef FullName' => 159,
			'BuildAssemblyAdd SerialNumber' => 4095,
			'BuildAssemblyAdd LotNumber' => 40,
			'BuildAssemblyAdd TxnDate' => 0,
			'BuildAssemblyAdd RefNumber' => 11,
			'BuildAssemblyAdd Memo' => 4095,
			'BuildAssemblyAdd QuantityToBuild' => 0,
			'BuildAssemblyAdd MarkPendingIfRequired' => 0,
			'BuildAssemblyAdd ExternalGUID' => 0,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'BuildAssemblyAdd ItemInventoryAssemblyRef ListID' => 999.99,
			'BuildAssemblyAdd ItemInventoryAssemblyRef FullName' => 999.99,
			'BuildAssemblyAdd InventorySiteRef ListID' => 999.99,
			'BuildAssemblyAdd InventorySiteRef FullName' => 999.99,
			'BuildAssemblyAdd InventorySiteLocationRef ListID' => 999.99,
			'BuildAssemblyAdd InventorySiteLocationRef FullName' => 999.99,
			'BuildAssemblyAdd SerialNumber' => 999.99,
			'BuildAssemblyAdd LotNumber' => 999.99,
			'BuildAssemblyAdd TxnDate' => 999.99,
			'BuildAssemblyAdd RefNumber' => 999.99,
			'BuildAssemblyAdd Memo' => 999.99,
			'BuildAssemblyAdd QuantityToBuild' => 999.99,
			'BuildAssemblyAdd MarkPendingIfRequired' => 7.0,
			'BuildAssemblyAdd ExternalGUID' => 9.0,
			'IncludeRetElement' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'BuildAssemblyAdd ItemInventoryAssemblyRef ListID' => false,
			'BuildAssemblyAdd ItemInventoryAssemblyRef FullName' => false,
			'BuildAssemblyAdd InventorySiteRef ListID' => false,
			'BuildAssemblyAdd InventorySiteRef FullName' => false,
			'BuildAssemblyAdd InventorySiteLocationRef ListID' => false,
			'BuildAssemblyAdd InventorySiteLocationRef FullName' => false,
			'BuildAssemblyAdd SerialNumber' => false,
			'BuildAssemblyAdd LotNumber' => false,
			'BuildAssemblyAdd TxnDate' => false,
			'BuildAssemblyAdd RefNumber' => false,
			'BuildAssemblyAdd Memo' => false,
			'BuildAssemblyAdd QuantityToBuild' => false,
			'BuildAssemblyAdd MarkPendingIfRequired' => false,
			'BuildAssemblyAdd ExternalGUID' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'BuildAssemblyAdd',
			'BuildAssemblyAdd ItemInventoryAssemblyRef',
			'BuildAssemblyAdd ItemInventoryAssemblyRef ListID',
			'BuildAssemblyAdd ItemInventoryAssemblyRef FullName',
			'BuildAssemblyAdd InventorySiteRef ListID',
			'BuildAssemblyAdd InventorySiteRef FullName',
			'BuildAssemblyAdd InventorySiteLocationRef ListID',
			'BuildAssemblyAdd InventorySiteLocationRef FullName',
			'BuildAssemblyAdd SerialNumber',
			'BuildAssemblyAdd LotNumber',
			'BuildAssemblyAdd TxnDate',
			'BuildAssemblyAdd RefNumber',
			'BuildAssemblyAdd Memo',
			'BuildAssemblyAdd QuantityToBuild',
			'BuildAssemblyAdd MarkPendingIfRequired',
			'BuildAssemblyAdd ExternalGUID',
			'IncludeRetElement',
		];

		return $paths;
	}
}
