<?php declare(strict_types=1);

/**
 * Schema object for: ChargeModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class ChargeModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'ChargeMod';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TxnID' => 'IDTYPE',
		'EditSequence' => 'STRTYPE',
		'CustomerRef ListID' => 'IDTYPE',
		'CustomerRef FullName' => 'STRTYPE',
		'TxnDate' => 'DATETYPE',
		'RefNumber' => 'STRTYPE',
		'ItemRef ListID' => 'IDTYPE',
		'ItemRef FullName' => 'STRTYPE',
		'InventorySiteRef ListID' => 'IDTYPE',
		'InventorySiteRef FullName' => 'STRTYPE',
		'InventorySiteLocationRef ListID' => 'IDTYPE',
		'InventorySiteLocationRef FullName' => 'STRTYPE',
		'Quantity' => 'QUANTYPE',
		'UnitOfMeasure' => 'STRTYPE',
		'OverrideUOMSetRef ListID' => 'IDTYPE',
		'OverrideUOMSetRef FullName' => 'STRTYPE',
		'Rate' => 'PRICETYPE',
		'OptionForPriceRuleConflict' => 'ENUMTYPE',
		'Amount' => 'AMTTYPE',
		'Desc' => 'STRTYPE',
		'ARAccountRef ListID' => 'IDTYPE',
		'ARAccountRef FullName' => 'STRTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'BilledDate' => 'DATETYPE',
		'DueDate' => 'DATETYPE',
		'OverrideItemAccountRef ListID' => 'IDTYPE',
		'OverrideItemAccountRef FullName' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'EditSequence' => 16,
		'CustomerRef FullName' => 209,
		'RefNumber' => 11,
		'InventorySiteRef FullName' => 31,
		'InventorySiteLocationRef FullName' => 31,
		'UnitOfMeasure' => 31,
		'OverrideUOMSetRef FullName' => 31,
		'Desc' => 4095,
		'ARAccountRef FullName' => 159,
		'ClassRef FullName' => 159,
		'OverrideItemAccountRef FullName' => 159,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'InventorySiteRef ListID' => 10.0,
		'InventorySiteRef FullName' => 10.0,
		'InventorySiteLocationRef ListID' => 12.0,
		'InventorySiteLocationRef FullName' => 12.0,
		'UnitOfMeasure' => 7.0,
		'OverrideUOMSetRef ListID' => 7.0,
		'OverrideUOMSetRef FullName' => 7.0,
		'OptionForPriceRuleConflict' => 13.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'InventorySiteRef ListID' => ['AU'],
		'InventorySiteRef FullName' => ['AU'],
		'InventorySiteLocationRef ListID' => ['AU'],
		'InventorySiteLocationRef FullName' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TxnID',
		'EditSequence',
		'CustomerRef',
		'CustomerRef ListID',
		'CustomerRef FullName',
		'TxnDate',
		'RefNumber',
		'ItemRef',
		'ItemRef ListID',
		'ItemRef FullName',
		'InventorySiteRef',
		'InventorySiteRef ListID',
		'InventorySiteRef FullName',
		'InventorySiteLocationRef',
		'InventorySiteLocationRef ListID',
		'InventorySiteLocationRef FullName',
		'Quantity',
		'UnitOfMeasure',
		'OverrideUOMSetRef',
		'OverrideUOMSetRef ListID',
		'OverrideUOMSetRef FullName',
		'Rate',
		'OptionForPriceRuleConflict',
		'Amount',
		'Desc',
		'ARAccountRef',
		'ARAccountRef ListID',
		'ARAccountRef FullName',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'BilledDate',
		'DueDate',
		'OverrideItemAccountRef',
		'OverrideItemAccountRef ListID',
		'OverrideItemAccountRef FullName',
		'IncludeRetElement',
	];
}
