<?php declare(strict_types=1);

/**
 * Schema object for: DataExtAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class DataExtAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'DataExtAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'OwnerID' => 'GUIDTYPE',
		'DataExtName' => 'STRTYPE',
		'ListDataExtType' => 'ENUMTYPE',
		'ListObjRef ListID' => 'IDTYPE',
		'ListObjRef FullName' => 'STRTYPE',
		'TxnDataExtType' => 'ENUMTYPE',
		'TxnID' => 'IDTYPE',
		'TxnLineID' => 'IDTYPE',
		'OtherDataExtType' => 'ENUMTYPE',
		'DataExtValue' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'DataExtName' => 31,
		'ListObjRef FullName' => 159,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'TxnLineID' => 3.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'ListDataExtType' => ['OE'],
		'ListObjRef ListID' => ['OE'],
		'ListObjRef FullName' => ['OE'],
		'TxnDataExtType' => ['OE'],
		'TxnID' => ['OE'],
		'TxnLineID' => ['OE'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'OwnerID',
		'DataExtName',
		'ListDataExtType',
		'ListObjRef',
		'ListObjRef ListID',
		'ListObjRef FullName',
		'TxnDataExtType',
		'TxnID',
		'TxnLineID',
		'OtherDataExtType',
		'DataExtValue',
	];
}
