<?php declare(strict_types=1);

/**
 * Schema object for: DataEventSubscriptionAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class DataEventSubscriptionAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'DataEventSubscriptionAdd SubscriberID' => 'GUIDTYPE',
			'DataEventSubscriptionAdd COMCallbackInfo AppName' => 'STRTYPE',
			'DataEventSubscriptionAdd COMCallbackInfo ProgID' => 'STRTYPE',
			'DataEventSubscriptionAdd COMCallbackInfo CLSID' => 'GUIDTYPE',
			'DataEventSubscriptionAdd DeliveryPolicy' => 'ENUMTYPE',
			'DataEventSubscriptionAdd TrackLostEvents' => 'ENUMTYPE',
			'DataEventSubscriptionAdd DeliverOwnEvents' => 'BOOLTYPE',
			'DataEventSubscriptionAdd ListEventSubscription ListEventType' => 'ENUMTYPE',
			'DataEventSubscriptionAdd ListEventSubscription ListEventOperation' => 'ENUMTYPE',
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventType' => 'ENUMTYPE',
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventOperation' => 'ENUMTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'DataEventSubscriptionAdd SubscriberID' => 0,
			'DataEventSubscriptionAdd COMCallbackInfo AppName' => 128,
			'DataEventSubscriptionAdd COMCallbackInfo ProgID' => 128,
			'DataEventSubscriptionAdd COMCallbackInfo CLSID' => 0,
			'DataEventSubscriptionAdd DeliveryPolicy' => 0,
			'DataEventSubscriptionAdd TrackLostEvents' => 0,
			'DataEventSubscriptionAdd DeliverOwnEvents' => 0,
			'DataEventSubscriptionAdd ListEventSubscription ListEventType' => 0,
			'DataEventSubscriptionAdd ListEventSubscription ListEventOperation' => 0,
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventType' => 0,
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventOperation' => 0,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'DataEventSubscriptionAdd SubscriberID' => 999.99,
			'DataEventSubscriptionAdd COMCallbackInfo AppName' => 999.99,
			'DataEventSubscriptionAdd COMCallbackInfo ProgID' => 999.99,
			'DataEventSubscriptionAdd COMCallbackInfo CLSID' => 999.99,
			'DataEventSubscriptionAdd DeliveryPolicy' => 999.99,
			'DataEventSubscriptionAdd TrackLostEvents' => 999.99,
			'DataEventSubscriptionAdd DeliverOwnEvents' => 4.0,
			'DataEventSubscriptionAdd ListEventSubscription ListEventType' => 999.99,
			'DataEventSubscriptionAdd ListEventSubscription ListEventOperation' => 999.99,
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventType' => 999.99,
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventOperation' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'DataEventSubscriptionAdd SubscriberID' => false,
			'DataEventSubscriptionAdd COMCallbackInfo AppName' => false,
			'DataEventSubscriptionAdd COMCallbackInfo ProgID' => false,
			'DataEventSubscriptionAdd COMCallbackInfo CLSID' => false,
			'DataEventSubscriptionAdd DeliveryPolicy' => false,
			'DataEventSubscriptionAdd TrackLostEvents' => false,
			'DataEventSubscriptionAdd DeliverOwnEvents' => false,
			'DataEventSubscriptionAdd ListEventSubscription ListEventType' => true,
			'DataEventSubscriptionAdd ListEventSubscription ListEventOperation' => true,
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventType' => true,
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventOperation' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'DataEventSubscriptionAdd',
			'DataEventSubscriptionAdd SubscriberID',
			'DataEventSubscriptionAdd COMCallbackInfo AppName',
			'DataEventSubscriptionAdd COMCallbackInfo ProgID',
			'DataEventSubscriptionAdd COMCallbackInfo CLSID',
			'DataEventSubscriptionAdd DeliveryPolicy',
			'DataEventSubscriptionAdd TrackLostEvents',
			'DataEventSubscriptionAdd DeliverOwnEvents',
			'DataEventSubscriptionAdd ListEventSubscription ListEventType',
			'DataEventSubscriptionAdd ListEventSubscription ListEventOperation',
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventType',
			'DataEventSubscriptionAdd TxnEventSubscription TxnEventOperation',
		];

		return $paths;
	}
}
