<?php declare(strict_types=1);

/**
 * Schema object for: DataExtDefAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class DataExtDefAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = 'DataExtDefAdd';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'OwnerID' => 'GUIDTYPE',
			'DataExtName' => 'STRTYPE',
			'DataExtType' => 'ENUMTYPE',
			'AssignToObject' => 'ENUMTYPE',
			'DataExtListRequire' => 'BOOLTYPE',
			'DataExtTxnRequire' => 'BOOLTYPE',
			'DataExtFormatString' => 'STRTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'OwnerID' => 0,
			'DataExtName' => 31,
			'DataExtType' => 0,
			'AssignToObject' => 0,
			'DataExtListRequire' => 0,
			'DataExtTxnRequire' => 0,
			'DataExtFormatString' => 0,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'OwnerID' => 999.99,
			'DataExtName' => 999.99,
			'DataExtType' => 999.99,
			'AssignToObject' => 999.99,
			'DataExtListRequire' => 12.0,
			'DataExtTxnRequire' => 12.0,
			'DataExtFormatString' => 12.0,
			'IncludeRetElement' => 4.0,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'OwnerID' => false,
			'DataExtName' => false,
			'DataExtType' => false,
			'AssignToObject' => true,
			'DataExtListRequire' => false,
			'DataExtTxnRequire' => false,
			'DataExtFormatString' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'OwnerID',
			'DataExtName',
			'DataExtType',
			'AssignToObject',
			'DataExtListRequire',
			'DataExtTxnRequire',
			'DataExtFormatString',
			'IncludeRetElement',
		];

		return $paths;
	}
}
