<?php declare(strict_types=1);

/**
 * Schema object for: DepartmentQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbposxmlops30.xml file in this package.
 */
final class DepartmentQueryRq extends AbstractSchemaObject
{
	/**
	 * This QuickBooks Action is found only in the QuickBooks Point of Sale (QBPOS) sdk.
	 * @var bool
	 */
	protected $_isQbxmlPosOnly = true;

	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'MaxReturned' => 'INTTYPE',
		'OwnerID' => 'GUIDTYPE',
		'ListID' => 'IDTYPE',
		'TimeCreatedFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TimeCreatedFilter TimeCreated' => 'DATETIMETYPE',
		'TimeCreatedRangeFilter FromTimeCreated' => 'DATETIMETYPE',
		'TimeCreatedRangeFilter ToTimeCreated' => 'DATETIMETYPE',
		'TimeModifiedFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TimeModifiedFilter TimeModified' => 'DATETIMETYPE',
		'TimeModifiedRangeFilter FromTimeModified' => 'DATETIMETYPE',
		'TimeModifiedRangeFilter ToTimeModified' => 'DATETIMETYPE',
		'DefaultMarginPercentFilter MatchNumericCriterion' => 'ENUMTYPE',
		'DefaultMarginPercentFilter DefaultMarginPercent' => 'INTTYPE',
		'DefaultMarginPercentRangeFilter FromDefaultMarginPercent' => 'INTTYPE',
		'DefaultMarginPercentRangeFilter ToDefaultMarginPercent' => 'INTTYPE',
		'DepartmentCodeFilter MatchStringCriterion' => 'ENUMTYPE',
		'DepartmentCodeFilter DepartmentCode' => 'STRTYPE',
		'DepartmentCodeRangeFilter FromDepartmentCode' => 'STRTYPE',
		'DepartmentCodeRangeFilter ToDepartmentCode' => 'STRTYPE',
		'DepartmentNameFilter MatchStringCriterion' => 'ENUMTYPE',
		'DepartmentNameFilter DepartmentName' => 'STRTYPE',
		'DepartmentNameRangeFilter FromDepartmentName' => 'STRTYPE',
		'DepartmentNameRangeFilter ToDepartmentName' => 'STRTYPE',
		'StoreExchangeStatus' => 'ENUMTYPE',
		'TaxCode' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'DepartmentCodeFilter DepartmentCode' => 3,
		'DepartmentCodeRangeFilter FromDepartmentCode' => 3,
		'DepartmentCodeRangeFilter ToDepartmentCode' => 3,
		'DepartmentNameFilter DepartmentName' => 30,
		'DepartmentNameRangeFilter FromDepartmentName' => 30,
		'DepartmentNameRangeFilter ToDepartmentName' => 30,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'IncludeRetElement' => 2.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'OwnerID' => true,
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'MaxReturned',
		'OwnerID',
		'ListID',
		'TimeCreatedFilter',
		'TimeCreatedFilter MatchNumericCriterion',
		'TimeCreatedFilter TimeCreated',
		'TimeCreatedRangeFilter',
		'TimeCreatedRangeFilter FromTimeCreated',
		'TimeCreatedRangeFilter ToTimeCreated',
		'TimeModifiedFilter',
		'TimeModifiedFilter MatchNumericCriterion',
		'TimeModifiedFilter TimeModified',
		'TimeModifiedRangeFilter',
		'TimeModifiedRangeFilter FromTimeModified',
		'TimeModifiedRangeFilter ToTimeModified',
		'DefaultMarginPercentFilter',
		'DefaultMarginPercentFilter MatchNumericCriterion',
		'DefaultMarginPercentFilter DefaultMarginPercent',
		'DefaultMarginPercentRangeFilter',
		'DefaultMarginPercentRangeFilter FromDefaultMarginPercent',
		'DefaultMarginPercentRangeFilter ToDefaultMarginPercent',
		'DepartmentCodeFilter',
		'DepartmentCodeFilter MatchStringCriterion',
		'DepartmentCodeFilter DepartmentCode',
		'DepartmentCodeRangeFilter',
		'DepartmentCodeRangeFilter FromDepartmentCode',
		'DepartmentCodeRangeFilter ToDepartmentCode',
		'DepartmentNameFilter',
		'DepartmentNameFilter MatchStringCriterion',
		'DepartmentNameFilter DepartmentName',
		'DepartmentNameRangeFilter',
		'DepartmentNameRangeFilter FromDepartmentName',
		'DepartmentNameRangeFilter ToDepartmentName',
		'StoreExchangeStatus',
		'TaxCode',
		'IncludeRetElement',
	];
}
