<?php declare(strict_types=1);

/**
 * Schema object for: DepositQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class DepositQueryRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'TxnID' => 'IDTYPE',
			'MaxReturned' => 'INTTYPE',
			'ModifiedDateRangeFilter FromModifiedDate' => 'DATETIMETYPE',
			'ModifiedDateRangeFilter ToModifiedDate' => 'DATETIMETYPE',
			'TxnDateRangeFilter FromTxnDate' => 'DATETYPE',
			'TxnDateRangeFilter ToTxnDate' => 'DATETYPE',
			'TxnDateRangeFilter DateMacro' => 'ENUMTYPE',
			'EntityFilter ListID' => 'IDTYPE',
			'EntityFilter FullName' => 'STRTYPE',
			'EntityFilter ListIDWithChildren' => 'IDTYPE',
			'EntityFilter FullNameWithChildren' => 'STRTYPE',
			'AccountFilter ListID' => 'IDTYPE',
			'AccountFilter FullName' => 'STRTYPE',
			'AccountFilter ListIDWithChildren' => 'IDTYPE',
			'AccountFilter FullNameWithChildren' => 'STRTYPE',
			'CurrencyFilter ListID' => 'IDTYPE',
			'CurrencyFilter FullName' => 'STRTYPE',
			'IncludeLineItems' => 'BOOLTYPE',
			'IncludeRetElement' => 'STRTYPE',
			'OwnerID' => 'GUIDTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'TxnID' => 0,
			'MaxReturned' => 0,
			'ModifiedDateRangeFilter FromModifiedDate' => 0,
			'ModifiedDateRangeFilter ToModifiedDate' => 0,
			'TxnDateRangeFilter FromTxnDate' => 0,
			'TxnDateRangeFilter ToTxnDate' => 0,
			'TxnDateRangeFilter DateMacro' => 0,
			'EntityFilter ListID' => 0,
			'EntityFilter FullName' => 0,
			'EntityFilter ListIDWithChildren' => 0,
			'EntityFilter FullNameWithChildren' => 0,
			'AccountFilter ListID' => 0,
			'AccountFilter FullName' => 0,
			'AccountFilter ListIDWithChildren' => 0,
			'AccountFilter FullNameWithChildren' => 0,
			'CurrencyFilter ListID' => 0,
			'CurrencyFilter FullName' => 0,
			'IncludeLineItems' => 0,
			'IncludeRetElement' => 50,
			'OwnerID' => 0,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'TxnID' => 999.99,
			'MaxReturned' => 999.99,
			'ModifiedDateRangeFilter FromModifiedDate' => 999.99,
			'ModifiedDateRangeFilter ToModifiedDate' => 999.99,
			'TxnDateRangeFilter FromTxnDate' => 999.99,
			'TxnDateRangeFilter ToTxnDate' => 999.99,
			'TxnDateRangeFilter DateMacro' => 999.99,
			'EntityFilter ListID' => 2.0,
			'EntityFilter FullName' => 999.99,
			'EntityFilter ListIDWithChildren' => 2.0,
			'EntityFilter FullNameWithChildren' => 999.99,
			'AccountFilter ListID' => 2.0,
			'AccountFilter FullName' => 999.99,
			'AccountFilter ListIDWithChildren' => 2.0,
			'AccountFilter FullNameWithChildren' => 999.99,
			'CurrencyFilter ListID' => 2.0,
			'CurrencyFilter FullName' => 999.99,
			'IncludeLineItems' => 999.99,
			'IncludeRetElement' => 4.0,
			'OwnerID' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'TxnID' => true,
			'MaxReturned' => false,
			'ModifiedDateRangeFilter FromModifiedDate' => false,
			'ModifiedDateRangeFilter ToModifiedDate' => false,
			'TxnDateRangeFilter FromTxnDate' => false,
			'TxnDateRangeFilter ToTxnDate' => false,
			'TxnDateRangeFilter DateMacro' => false,
			'EntityFilter ListID' => true,
			'EntityFilter FullName' => true,
			'EntityFilter ListIDWithChildren' => false,
			'EntityFilter FullNameWithChildren' => false,
			'AccountFilter ListID' => true,
			'AccountFilter FullName' => true,
			'AccountFilter ListIDWithChildren' => false,
			'AccountFilter FullNameWithChildren' => false,
			'CurrencyFilter ListID' => true,
			'CurrencyFilter FullName' => true,
			'IncludeLineItems' => false,
			'IncludeRetElement' => true,
			'OwnerID' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'TxnID',
			'MaxReturned',
			'ModifiedDateRangeFilter',
			'ModifiedDateRangeFilter FromModifiedDate',
			'ModifiedDateRangeFilter ToModifiedDate',
			'TxnDateRangeFilter',
			'TxnDateRangeFilter FromTxnDate',
			'TxnDateRangeFilter ToTxnDate',
			'TxnDateRangeFilter DateMacro',
			'EntityFilter',
			'EntityFilter ListID',
			'EntityFilter FullName',
			'EntityFilter ListIDWithChildren',
			'EntityFilter FullNameWithChildren',
			'AccountFilter',
			'AccountFilter ListID',
			'AccountFilter FullName',
			'AccountFilter ListIDWithChildren',
			'AccountFilter FullNameWithChildren',
			'CurrencyFilter',
			'CurrencyFilter ListID',
			'CurrencyFilter FullName',
			'IncludeLineItems',
			'IncludeRetElement',
			'OwnerID',
		];

		return $paths;
	}
}
