<?php declare(strict_types=1);

/**
 * Schema object for: DepositAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class DepositAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'DepositAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TxnDate' => 'DATETYPE',
		'DepositToAccountRef ListID' => 'IDTYPE',
		'DepositToAccountRef FullName' => 'STRTYPE',
		'Memo' => 'STRTYPE',
		'CashBackInfoAdd AccountRef ListID' => 'IDTYPE',
		'CashBackInfoAdd AccountRef FullName' => 'STRTYPE',
		'CashBackInfoAdd Memo' => 'STRTYPE',
		'CashBackInfoAdd Amount' => 'AMTTYPE',
		'CurrencyRef ListID' => 'IDTYPE',
		'CurrencyRef FullName' => 'STRTYPE',
		'ExchangeRate' => 'FLOATTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'DepositLineAdd PaymentTxnID' => 'IDTYPE',
		'DepositLineAdd PaymentTxnLineID' => 'IDTYPE',
		'DepositLineAdd OverrideMemo' => 'STRTYPE',
		'DepositLineAdd OverrideCheckNumber' => 'STRTYPE',
		'DepositLineAdd OverrideClassRef ListID' => 'IDTYPE',
		'DepositLineAdd OverrideClassRef FullName' => 'STRTYPE',
		'DepositLineAdd EntityRef ListID' => 'IDTYPE',
		'DepositLineAdd EntityRef FullName' => 'STRTYPE',
		'DepositLineAdd AccountRef ListID' => 'IDTYPE',
		'DepositLineAdd AccountRef FullName' => 'STRTYPE',
		'DepositLineAdd Memo' => 'STRTYPE',
		'DepositLineAdd CheckNumber' => 'STRTYPE',
		'DepositLineAdd PaymentMethodRef ListID' => 'IDTYPE',
		'DepositLineAdd PaymentMethodRef FullName' => 'STRTYPE',
		'DepositLineAdd ClassRef ListID' => 'IDTYPE',
		'DepositLineAdd ClassRef FullName' => 'STRTYPE',
		'DepositLineAdd Amount' => 'AMTTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'DepositToAccountRef FullName' => 159,
		'Memo' => 4095,
		'CashBackInfoAdd AccountRef FullName' => 159,
		'CashBackInfoAdd Memo' => 4095,
		'CurrencyRef FullName' => 64,
		'DepositLineAdd OverrideMemo' => 4095,
		'DepositLineAdd OverrideCheckNumber' => 11,
		'DepositLineAdd OverrideClassRef FullName' => 159,
		'DepositLineAdd EntityRef FullName' => 209,
		'DepositLineAdd AccountRef FullName' => 159,
		'DepositLineAdd Memo' => 4095,
		'DepositLineAdd CheckNumber' => 11,
		'DepositLineAdd PaymentMethodRef FullName' => 31,
		'DepositLineAdd ClassRef FullName' => 159,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'CurrencyRef ListID' => 8.0,
		'CurrencyRef FullName' => 8.0,
		'ExchangeRate' => 8.0,
		'ExternalGUID' => 9.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TxnDate',
		'DepositToAccountRef',
		'DepositToAccountRef ListID',
		'DepositToAccountRef FullName',
		'Memo',
		'CashBackInfoAdd',
		'CashBackInfoAdd AccountRef',
		'CashBackInfoAdd AccountRef ListID',
		'CashBackInfoAdd AccountRef FullName',
		'CashBackInfoAdd Memo',
		'CashBackInfoAdd Amount',
		'CurrencyRef',
		'CurrencyRef ListID',
		'CurrencyRef FullName',
		'ExchangeRate',
		'ExternalGUID',
		'DepositLineAdd',
		'DepositLineAdd PaymentTxnID',
		'DepositLineAdd PaymentTxnLineID',
		'DepositLineAdd OverrideMemo',
		'DepositLineAdd OverrideCheckNumber',
		'DepositLineAdd OverrideClassRef ListID',
		'DepositLineAdd OverrideClassRef FullName',
		'DepositLineAdd EntityRef ListID',
		'DepositLineAdd EntityRef FullName',
		'DepositLineAdd AccountRef ListID',
		'DepositLineAdd AccountRef FullName',
		'DepositLineAdd Memo',
		'DepositLineAdd CheckNumber',
		'DepositLineAdd PaymentMethodRef ListID',
		'DepositLineAdd PaymentMethodRef FullName',
		'DepositLineAdd ClassRef ListID',
		'DepositLineAdd ClassRef FullName',
		'DepositLineAdd Amount',
		'IncludeRetElement',
	];
}
