<?php declare(strict_types=1);

/**
 * Schema object for: Form1099CategoryAccountMappingModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class Form1099CategoryAccountMappingModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'Form1099CategoryAccountMappingMod IsFiling1099Misc' => 'BOOLTYPE',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingCategory' => 'ENUMTYPE',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount AccountRef ListID' => 'IDTYPE',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount AccountRef FullName' => 'STRTYPE',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount ForceMapping' => 'BOOLTYPE',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod Threshold' => 'AMTTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount AccountRef FullName' => 159,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'Form1099CategoryAccountMappingMod',
		'Form1099CategoryAccountMappingMod IsFiling1099Misc',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingCategory',
		'Form1099CategoryAccountMappingMod',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount AccountRef',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount AccountRef ListID',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount AccountRef FullName',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod MappingAccount ForceMapping',
		'Form1099CategoryAccountMappingMod CategoryAccountMappingMod Threshold',
	];
}
