<?php declare(strict_types=1);

/**
 * Schema object for: InventoryAdjustmentModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class InventoryAdjustmentModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'InventoryAdjustmentMod TxnID' => 'IDTYPE',
		'InventoryAdjustmentMod EditSequence' => 'STRTYPE',
		'InventoryAdjustmentMod AccountRef ListID' => 'IDTYPE',
		'InventoryAdjustmentMod AccountRef FullName' => 'STRTYPE',
		'InventoryAdjustmentMod InventorySiteRef ListID' => 'IDTYPE',
		'InventoryAdjustmentMod InventorySiteRef FullName' => 'STRTYPE',
		'InventoryAdjustmentMod TxnDate' => 'DATETYPE',
		'InventoryAdjustmentMod RefNumber' => 'STRTYPE',
		'InventoryAdjustmentMod CustomerRef ListID' => 'IDTYPE',
		'InventoryAdjustmentMod CustomerRef FullName' => 'STRTYPE',
		'InventoryAdjustmentMod ClassRef ListID' => 'IDTYPE',
		'InventoryAdjustmentMod ClassRef FullName' => 'STRTYPE',
		'InventoryAdjustmentMod Memo' => 'STRTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod TxnLineID' => 'IDTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod ItemRef ListID' => 'IDTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod ItemRef FullName' => 'STRTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod SerialNumber' => 'STRTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod LotNumber' => 'STRTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod CountAdjustment' => 'INTTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef ListID' => 'IDTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef FullName' => 'STRTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod QuantityDifference' => 'QUANTYPE',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod ValueDifference' => 'AMTTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'InventoryAdjustmentMod EditSequence' => 16,
		'InventoryAdjustmentMod AccountRef FullName' => 159,
		'InventoryAdjustmentMod InventorySiteRef FullName' => 31,
		'InventoryAdjustmentMod RefNumber' => 11,
		'InventoryAdjustmentMod CustomerRef FullName' => 209,
		'InventoryAdjustmentMod ClassRef FullName' => 159,
		'InventoryAdjustmentMod Memo' => 4095,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod SerialNumber' => 4095,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod LotNumber' => 40,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef FullName' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'InventoryAdjustmentMod InventorySiteRef ListID' => 10.0,
		'InventoryAdjustmentMod InventorySiteRef FullName' => 10.0,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod SerialNumber' => 11.0,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod LotNumber' => 11.0,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod CountAdjustment' => 11.0,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef ListID' => 12.0,
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef FullName' => 12.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'InventoryAdjustmentMod InventorySiteRef ListID' => ['AU'],
		'InventoryAdjustmentMod InventorySiteRef FullName' => ['AU'],
		'InventoryAdjustmentMod InventoryAdjustmentLineMod SerialNumber' => ['AU'],
		'InventoryAdjustmentMod InventoryAdjustmentLineMod LotNumber' => ['AU'],
		'InventoryAdjustmentMod InventoryAdjustmentLineMod CountAdjustment' => ['AU'],
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef ListID' => ['AU'],
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef FullName' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'InventoryAdjustmentMod',
		'InventoryAdjustmentMod TxnID',
		'InventoryAdjustmentMod EditSequence',
		'InventoryAdjustmentMod AccountRef ListID',
		'InventoryAdjustmentMod AccountRef FullName',
		'InventoryAdjustmentMod InventorySiteRef ListID',
		'InventoryAdjustmentMod InventorySiteRef FullName',
		'InventoryAdjustmentMod TxnDate',
		'InventoryAdjustmentMod RefNumber',
		'InventoryAdjustmentMod CustomerRef ListID',
		'InventoryAdjustmentMod CustomerRef FullName',
		'InventoryAdjustmentMod ClassRef ListID',
		'InventoryAdjustmentMod ClassRef FullName',
		'InventoryAdjustmentMod Memo',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod TxnLineID',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod ItemRef ListID',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod ItemRef FullName',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod SerialNumber',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod LotNumber',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod CountAdjustment',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef ListID',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod InventorySiteLocationRef FullName',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod QuantityDifference',
		'InventoryAdjustmentMod InventoryAdjustmentLineMod ValueDifference',
		'IncludeRetElement',
	];
}
