<?php declare(strict_types=1);

/**
 * Schema object for: InventoryAdjustmentAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class InventoryAdjustmentAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'InventoryAdjustmentAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'AccountRef ListID' => 'IDTYPE',
		'AccountRef FullName' => 'STRTYPE',
		'TxnDate' => 'DATETYPE',
		'RefNumber' => 'STRTYPE',
		'InventorySiteRef ListID' => 'IDTYPE',
		'InventorySiteRef FullName' => 'STRTYPE',
		'CustomerRef ListID' => 'IDTYPE',
		'CustomerRef FullName' => 'STRTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'Memo' => 'STRTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'InventoryAdjustmentLineAdd ItemRef ListID' => 'IDTYPE',
		'InventoryAdjustmentLineAdd ItemRef FullName' => 'STRTYPE',
		'InventoryAdjustmentLineAdd QuantityAdjustment NewQuantity' => 'QUANTYPE',
		'InventoryAdjustmentLineAdd QuantityAdjustment QuantityDifference' => 'QUANTYPE',
		'InventoryAdjustmentLineAdd QuantityAdjustment SerialNumber' => 'STRTYPE',
		'InventoryAdjustmentLineAdd QuantityAdjustment LotNumber' => 'STRTYPE',
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef ListID' => 'IDTYPE',
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef FullName' => 'STRTYPE',
		'InventoryAdjustmentLineAdd ValueAdjustment NewQuantity' => 'QUANTYPE',
		'InventoryAdjustmentLineAdd ValueAdjustment QuantityDifference' => 'QUANTYPE',
		'InventoryAdjustmentLineAdd ValueAdjustment NewValue' => 'AMTTYPE',
		'InventoryAdjustmentLineAdd ValueAdjustment ValueDifference' => 'AMTTYPE',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment AddSerialNumber' => 'STRTYPE',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment RemoveSerialNumber' => 'STRTYPE',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef ListID' => 'IDTYPE',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef FullName' => 'STRTYPE',
		'InventoryAdjustmentLineAdd LotNumberAdjustment LotNumber' => 'STRTYPE',
		'InventoryAdjustmentLineAdd LotNumberAdjustment CountAdjustment' => 'INTTYPE',
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef ListID' => 'IDTYPE',
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef FullName' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'AccountRef FullName' => 159,
		'RefNumber' => 11,
		'InventorySiteRef FullName' => 31,
		'CustomerRef FullName' => 209,
		'ClassRef FullName' => 159,
		'Memo' => 4095,
		'InventoryAdjustmentLineAdd QuantityAdjustment SerialNumber' => 4095,
		'InventoryAdjustmentLineAdd QuantityAdjustment LotNumber' => 40,
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef FullName' => 31,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment AddSerialNumber' => 4095,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment RemoveSerialNumber' => 4095,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef FullName' => 31,
		'InventoryAdjustmentLineAdd LotNumberAdjustment LotNumber' => 40,
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef FullName' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'InventorySiteRef ListID' => 10.0,
		'InventorySiteRef FullName' => 10.0,
		'ExternalGUID' => 9.0,
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef ListID' => 12.0,
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef FullName' => 12.0,
		'InventoryAdjustmentLineAdd ValueAdjustment QuantityDifference' => 10.0,
		'InventoryAdjustmentLineAdd ValueAdjustment ValueDifference' => 10.0,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment AddSerialNumber' => 11.0,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment RemoveSerialNumber' => 11.0,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef ListID' => 12.0,
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef FullName' => 12.0,
		'InventoryAdjustmentLineAdd LotNumberAdjustment LotNumber' => 11.0,
		'InventoryAdjustmentLineAdd LotNumberAdjustment CountAdjustment' => 11.0,
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef ListID' => 12.0,
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef FullName' => 12.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'InventorySiteRef ListID' => ['AU'],
		'InventorySiteRef FullName' => ['AU'],
		'InventoryAdjustmentLineAdd QuantityAdjustment SerialNumber' => ['AU'],
		'InventoryAdjustmentLineAdd QuantityAdjustment LotNumber' => ['AU'],
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef ListID' => ['AU'],
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef FullName' => ['AU'],
		'InventoryAdjustmentLineAdd SerialNumberAdjustment AddSerialNumber' => ['AU'],
		'InventoryAdjustmentLineAdd SerialNumberAdjustment RemoveSerialNumber' => ['AU'],
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef ListID' => ['AU'],
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef FullName' => ['AU'],
		'InventoryAdjustmentLineAdd LotNumberAdjustment LotNumber' => ['AU'],
		'InventoryAdjustmentLineAdd LotNumberAdjustment CountAdjustment' => ['AU'],
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef ListID' => ['AU'],
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef FullName' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'AccountRef',
		'AccountRef ListID',
		'AccountRef FullName',
		'TxnDate',
		'RefNumber',
		'InventorySiteRef',
		'InventorySiteRef ListID',
		'InventorySiteRef FullName',
		'CustomerRef',
		'CustomerRef ListID',
		'CustomerRef FullName',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'Memo',
		'ExternalGUID',
		'InventoryAdjustmentLineAdd',
		'InventoryAdjustmentLineAdd ItemRef',
		'InventoryAdjustmentLineAdd ItemRef ListID',
		'InventoryAdjustmentLineAdd ItemRef FullName',
		'InventoryAdjustmentLineAdd QuantityAdjustment NewQuantity',
		'InventoryAdjustmentLineAdd QuantityAdjustment QuantityDifference',
		'InventoryAdjustmentLineAdd QuantityAdjustment SerialNumber',
		'InventoryAdjustmentLineAdd QuantityAdjustment LotNumber',
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef ListID',
		'InventoryAdjustmentLineAdd QuantityAdjustment InventorySiteLocationRef FullName',
		'InventoryAdjustmentLineAdd ValueAdjustment NewQuantity',
		'InventoryAdjustmentLineAdd ValueAdjustment QuantityDifference',
		'InventoryAdjustmentLineAdd ValueAdjustment NewValue',
		'InventoryAdjustmentLineAdd ValueAdjustment ValueDifference',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment AddSerialNumber',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment RemoveSerialNumber',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef ListID',
		'InventoryAdjustmentLineAdd SerialNumberAdjustment InventorySiteLocationRef FullName',
		'InventoryAdjustmentLineAdd LotNumberAdjustment LotNumber',
		'InventoryAdjustmentLineAdd LotNumberAdjustment CountAdjustment',
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef ListID',
		'InventoryAdjustmentLineAdd LotNumberAdjustment InventorySiteLocationRef FullName',
		'IncludeRetElement',
	];
}
