<?php declare(strict_types=1);

/**
 * Schema object for: ItemSitesQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class ItemSitesQueryRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'ListID' => 'IDTYPE',
		'ItemTypeFilter' => 'ENUMTYPE',
		'ItemSiteFilter ItemFilter ListID' => 'IDTYPE',
		'ItemSiteFilter ItemFilter FullName' => 'STRTYPE',
		'ItemSiteFilter ItemFilter ListIDWithChildren' => 'IDTYPE',
		'ItemSiteFilter ItemFilter FullNameWithChildren' => 'STRTYPE',
		'ItemSiteFilter SiteFilter ListID' => 'IDTYPE',
		'ItemSiteFilter SiteFilter FullName' => 'STRTYPE',
		'MaxReturned' => 'INTTYPE',
		'ActiveStatus' => 'ENUMTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'ItemSiteFilter ItemFilter FullName' => 159,
		'ItemSiteFilter ItemFilter FullNameWithChildren' => 159,
		'ItemSiteFilter SiteFilter FullName' => 64,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'ListID' => true,
		'ItemSiteFilter ItemFilter ListID' => true,
		'ItemSiteFilter ItemFilter FullName' => true,
		'ItemSiteFilter SiteFilter ListID' => true,
		'ItemSiteFilter SiteFilter FullName' => true,
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'ListID',
		'ItemTypeFilter',
		'ItemSiteFilter',
		'ItemSiteFilter ItemFilter',
		'ItemSiteFilter ItemFilter ListID',
		'ItemSiteFilter ItemFilter FullName',
		'ItemSiteFilter ItemFilter ListIDWithChildren',
		'ItemSiteFilter ItemFilter FullNameWithChildren',
		'ItemSiteFilter SiteFilter ListID',
		'ItemSiteFilter SiteFilter FullName',
		'MaxReturned',
		'ActiveStatus',
		'IncludeRetElement',
	];
}
