<?php declare(strict_types=1);

/**
 * Schema object for: ItemGroupModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class ItemGroupModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'ItemGroupMod';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'ListID' => 'IDTYPE',
		'EditSequence' => 'STRTYPE',
		'Name' => 'STRTYPE',
		'BarCode BarCodeValue' => 'STRTYPE',
		'BarCode AssignEvenIfUsed' => 'BOOLTYPE',
		'BarCode AllowOverride' => 'BOOLTYPE',
		'IsActive' => 'BOOLTYPE',
		'ItemDesc' => 'STRTYPE',
		'UnitOfMeasureSetRef ListID' => 'IDTYPE',
		'UnitOfMeasureSetRef FullName' => 'STRTYPE',
		'ForceUOMChange' => 'BOOLTYPE',
		'IsPrintItemsInGroup' => 'BOOLTYPE',
		'ClearItemsInGroup' => 'BOOLTYPE',
		'ItemGroupLine ItemRef ListID' => 'IDTYPE',
		'ItemGroupLine ItemRef FullName' => 'STRTYPE',
		'ItemGroupLine Quantity' => 'QUANTYPE',
		'ItemGroupLine UnitOfMeasure' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'EditSequence' => 16,
		'Name' => 31,
		'BarCode BarCodeValue' => 50,
		'ItemDesc' => 4095,
		'UnitOfMeasureSetRef FullName' => 31,
		'ItemGroupLine UnitOfMeasure' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'BarCode BarCodeValue' => 12.0,
		'BarCode AssignEvenIfUsed' => 12.0,
		'BarCode AllowOverride' => 12.0,
		'UnitOfMeasureSetRef ListID' => 7.0,
		'UnitOfMeasureSetRef FullName' => 7.0,
		'ForceUOMChange' => 7.0,
		'ItemGroupLine UnitOfMeasure' => 7.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'BarCode BarCodeValue' => ['AU'],
		'BarCode AssignEvenIfUsed' => ['AU'],
		'BarCode AllowOverride' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'ListID',
		'EditSequence',
		'Name',
		'BarCode',
		'BarCode BarCodeValue',
		'BarCode AssignEvenIfUsed',
		'BarCode AllowOverride',
		'IsActive',
		'ItemDesc',
		'UnitOfMeasureSetRef',
		'UnitOfMeasureSetRef ListID',
		'UnitOfMeasureSetRef FullName',
		'ForceUOMChange',
		'IsPrintItemsInGroup',
		'ClearItemsInGroup',
		'ItemGroupLine',
		'ItemGroupLine ItemRef',
		'ItemGroupLine ItemRef ListID',
		'ItemGroupLine ItemRef FullName',
		'ItemGroupLine Quantity',
		'ItemGroupLine UnitOfMeasure',
		'IncludeRetElement',
	];
}
