<?php declare(strict_types=1);

/**
 * Schema object for: ItemAssembliesCanBuildQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class ItemAssembliesCanBuildQueryRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'ItemInventoryAssemblyRef ListID' => 'IDTYPE',
			'ItemInventoryAssemblyRef FullName' => 'STRTYPE',
			'TxnDate' => 'DATETYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'ItemInventoryAssemblyRef ListID' => 0,
			'ItemInventoryAssemblyRef FullName' => 159,
			'TxnDate' => 0,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'ItemInventoryAssemblyRef ListID' => 999.99,
			'ItemInventoryAssemblyRef FullName' => 999.99,
			'TxnDate' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'ItemInventoryAssemblyRef ListID' => false,
			'ItemInventoryAssemblyRef FullName' => false,
			'TxnDate' => false,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'ItemInventoryAssemblyRef',
			'ItemInventoryAssemblyRef ListID',
			'ItemInventoryAssemblyRef FullName',
			'TxnDate',
		];

		return $paths;
	}
}
