<?php declare(strict_types=1);

/**
 * Schema object for: ItemFixedAssetModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class ItemFixedAssetModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'ItemFixedAssetMod';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'ListID' => 'IDTYPE',
		'EditSequence' => 'STRTYPE',
		'Name' => 'STRTYPE',
		'BarCode BarCodeValue' => 'STRTYPE',
		'BarCode AssignEvenIfUsed' => 'BOOLTYPE',
		'BarCode AllowOverride' => 'BOOLTYPE',
		'IsActive' => 'BOOLTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'AcquiredAs' => 'ENUMTYPE',
		'PurchaseDesc' => 'STRTYPE',
		'PurchaseDate' => 'DATETYPE',
		'PurchaseCost' => 'PRICETYPE',
		'VendorOrPayeeName' => 'STRTYPE',
		'AssetAccountRef ListID' => 'IDTYPE',
		'AssetAccountRef FullName' => 'STRTYPE',
		'FixedAssetSalesInfoMod SalesDesc' => 'STRTYPE',
		'FixedAssetSalesInfoMod SalesDate' => 'DATETYPE',
		'FixedAssetSalesInfoMod SalesPrice' => 'PRICETYPE',
		'FixedAssetSalesInfoMod SalesExpense' => 'PRICETYPE',
		'AssetDesc' => 'STRTYPE',
		'Location' => 'STRTYPE',
		'PONumber' => 'STRTYPE',
		'SerialNumber' => 'STRTYPE',
		'WarrantyExpDate' => 'DATETYPE',
		'Notes' => 'STRTYPE',
		'AssetNumber' => 'STRTYPE',
		'CostBasis' => 'AMTTYPE',
		'YearEndAccumulatedDepreciation' => 'AMTTYPE',
		'YearEndBookValue' => 'AMTTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'EditSequence' => 16,
		'Name' => 31,
		'BarCode BarCodeValue' => 50,
		'ClassRef FullName' => 159,
		'PurchaseDesc' => 50,
		'VendorOrPayeeName' => 50,
		'AssetAccountRef FullName' => 159,
		'FixedAssetSalesInfoMod SalesDesc' => 50,
		'AssetDesc' => 50,
		'Location' => 50,
		'PONumber' => 30,
		'SerialNumber' => 30,
		'Notes' => 4095,
		'AssetNumber' => 10,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'BarCode BarCodeValue' => 12.0,
		'BarCode AssignEvenIfUsed' => 12.0,
		'BarCode AllowOverride' => 12.0,
		'ClassRef ListID' => 12.0,
		'ClassRef FullName' => 12.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'BarCode BarCodeValue' => ['AU'],
		'BarCode AssignEvenIfUsed' => ['AU'],
		'BarCode AllowOverride' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'ListID',
		'EditSequence',
		'Name',
		'BarCode',
		'BarCode BarCodeValue',
		'BarCode AssignEvenIfUsed',
		'BarCode AllowOverride',
		'IsActive',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'AcquiredAs',
		'PurchaseDesc',
		'PurchaseDate',
		'PurchaseCost',
		'VendorOrPayeeName',
		'AssetAccountRef',
		'AssetAccountRef ListID',
		'AssetAccountRef FullName',
		'FixedAssetSalesInfoMod',
		'FixedAssetSalesInfoMod SalesDesc',
		'FixedAssetSalesInfoMod SalesDate',
		'FixedAssetSalesInfoMod SalesPrice',
		'FixedAssetSalesInfoMod SalesExpense',
		'AssetDesc',
		'Location',
		'PONumber',
		'SerialNumber',
		'WarrantyExpDate',
		'Notes',
		'AssetNumber',
		'CostBasis',
		'YearEndAccumulatedDepreciation',
		'YearEndBookValue',
		'IncludeRetElement',
	];
}
