<?php declare(strict_types=1);

/**
 * Schema object for: JournalEntryAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class JournalEntryAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'JournalEntryAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TxnDate' => 'DATETYPE',
		'RefNumber' => 'STRTYPE',
		'Memo' => 'STRTYPE',
		'IsAdjustment' => 'BOOLTYPE',
		'IsHomeCurrencyAdjustment' => 'BOOLTYPE',
		'IsAmountsEnteredInHomeCurrency' => 'BOOLTYPE',
		'CurrencyRef ListID' => 'IDTYPE',
		'CurrencyRef FullName' => 'STRTYPE',
		'ExchangeRate' => 'FLOATTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'JournalDebitLine TxnLineID' => 'IDTYPE',
		'JournalDebitLine AccountRef ListID' => 'IDTYPE',
		'JournalDebitLine AccountRef FullName' => 'STRTYPE',
		'JournalDebitLine Amount' => 'AMTTYPE',
		'JournalDebitLine TaxAmount' => 'AMTTYPE',
		'JournalDebitLine Memo' => 'STRTYPE',
		'JournalDebitLine EntityRef ListID' => 'IDTYPE',
		'JournalDebitLine EntityRef FullName' => 'STRTYPE',
		'JournalDebitLine ClassRef ListID' => 'IDTYPE',
		'JournalDebitLine ClassRef FullName' => 'STRTYPE',
		'JournalDebitLine ItemSalesTaxRef ListID' => 'IDTYPE',
		'JournalDebitLine ItemSalesTaxRef FullName' => 'STRTYPE',
		'JournalDebitLine BillableStatus' => 'ENUMTYPE',
		'JournalCreditLine TxnLineID' => 'IDTYPE',
		'JournalCreditLine AccountRef ListID' => 'IDTYPE',
		'JournalCreditLine AccountRef FullName' => 'STRTYPE',
		'JournalCreditLine Amount' => 'AMTTYPE',
		'JournalCreditLine TaxAmount' => 'AMTTYPE',
		'JournalCreditLine Memo' => 'STRTYPE',
		'JournalCreditLine EntityRef ListID' => 'IDTYPE',
		'JournalCreditLine EntityRef FullName' => 'STRTYPE',
		'JournalCreditLine ClassRef ListID' => 'IDTYPE',
		'JournalCreditLine ClassRef FullName' => 'STRTYPE',
		'JournalCreditLine ItemSalesTaxRef ListID' => 'IDTYPE',
		'JournalCreditLine ItemSalesTaxRef FullName' => 'STRTYPE',
		'JournalCreditLine BillableStatus' => 'ENUMTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'RefNumber' => 11,
		'Memo' => 4000,
		'CurrencyRef FullName' => 64,
		'JournalDebitLine AccountRef FullName' => 159,
		'JournalDebitLine Memo' => 4095,
		'JournalDebitLine EntityRef FullName' => 209,
		'JournalDebitLine ClassRef FullName' => 159,
		'JournalDebitLine ItemSalesTaxRef FullName' => 31,
		'JournalCreditLine AccountRef FullName' => 159,
		'JournalCreditLine Memo' => 4095,
		'JournalCreditLine EntityRef FullName' => 209,
		'JournalCreditLine ClassRef FullName' => 159,
		'JournalCreditLine ItemSalesTaxRef FullName' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'IsAdjustment' => 3.0,
		'IsHomeCurrencyAdjustment' => 8.0,
		'IsAmountsEnteredInHomeCurrency' => 8.0,
		'CurrencyRef ListID' => 8.0,
		'CurrencyRef FullName' => 8.0,
		'ExchangeRate' => 8.0,
		'ExternalGUID' => 9.0,
		'JournalDebitLine TaxAmount' => 6.1,
		'JournalDebitLine ItemSalesTaxRef ListID' => 6.0,
		'JournalDebitLine ItemSalesTaxRef FullName' => 6.0,
		'JournalDebitLine BillableStatus' => 3.0,
		'JournalCreditLine TaxAmount' => 6.1,
		'JournalCreditLine ItemSalesTaxRef ListID' => 6.0,
		'JournalCreditLine ItemSalesTaxRef FullName' => 6.0,
		'JournalCreditLine BillableStatus' => 3.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'Memo' => ['US','CA','UK','AU'],
		'IsAdjustment' => ['OE'],
		'IsHomeCurrencyAdjustment' => ['OE'],
		'IsAmountsEnteredInHomeCurrency' => ['OE'],
		'CurrencyRef ListID' => ['OE'],
		'CurrencyRef FullName' => ['OE'],
		'ExchangeRate' => ['OE'],
		'ExternalGUID' => ['OE'],
		'JournalDebitLine TaxAmount' => ['US','CA','UK','OE'],
		'JournalDebitLine ItemSalesTaxRef ListID' => ['US','OE'],
		'JournalDebitLine ItemSalesTaxRef FullName' => ['US','OE'],
		'JournalDebitLine BillableStatus' => ['OE'],
		'JournalCreditLine TaxAmount' => ['US','CA','UK','OE'],
		'JournalCreditLine ItemSalesTaxRef ListID' => ['US','OE'],
		'JournalCreditLine ItemSalesTaxRef FullName' => ['US','OE'],
		'JournalCreditLine BillableStatus' => ['OE'],
		'IncludeRetElement' => ['OE'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TxnDate',
		'RefNumber',
		'Memo',
		'IsAdjustment',
		'IsHomeCurrencyAdjustment',
		'IsAmountsEnteredInHomeCurrency',
		'CurrencyRef',
		'CurrencyRef ListID',
		'CurrencyRef FullName',
		'ExchangeRate',
		'ExternalGUID',
		'JournalDebitLine',
		'JournalDebitLine TxnLineID',
		'JournalDebitLine AccountRef ListID',
		'JournalDebitLine AccountRef FullName',
		'JournalDebitLine Amount',
		'JournalDebitLine TaxAmount',
		'JournalDebitLine Memo',
		'JournalDebitLine EntityRef ListID',
		'JournalDebitLine EntityRef FullName',
		'JournalDebitLine ClassRef ListID',
		'JournalDebitLine ClassRef FullName',
		'JournalDebitLine ItemSalesTaxRef ListID',
		'JournalDebitLine ItemSalesTaxRef FullName',
		'JournalDebitLine BillableStatus',
		'JournalCreditLine',
		'JournalCreditLine TxnLineID',
		'JournalCreditLine AccountRef ListID',
		'JournalCreditLine AccountRef FullName',
		'JournalCreditLine Amount',
		'JournalCreditLine TaxAmount',
		'JournalCreditLine Memo',
		'JournalCreditLine EntityRef ListID',
		'JournalCreditLine EntityRef FullName',
		'JournalCreditLine ClassRef ListID',
		'JournalCreditLine ClassRef FullName',
		'JournalCreditLine ItemSalesTaxRef ListID',
		'JournalCreditLine ItemSalesTaxRef FullName',
		'JournalCreditLine BillableStatus',
		'IncludeRetElement',
	];
}
