<?php declare(strict_types=1);

/**
 * Schema object for: JournalEntryModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class JournalEntryModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'JournalEntryMod';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TxnID' => 'IDTYPE',
		'EditSequence' => 'STRTYPE',
		'TxnDate' => 'DATETYPE',
		'RefNumber' => 'STRTYPE',
		'IsAdjustment' => 'BOOLTYPE',
		'IsAmountsEnteredInHomeCurrency' => 'BOOLTYPE',
		'CurrencyRef ListID' => 'IDTYPE',
		'CurrencyRef FullName' => 'STRTYPE',
		'ExchangeRate' => 'FLOATTYPE',
		'JournalLineMod TxnLineID' => 'IDTYPE',
		'JournalLineMod JournalLineType' => 'ENUMTYPE',
		'JournalLineMod AccountRef ListID' => 'IDTYPE',
		'JournalLineMod AccountRef FullName' => 'STRTYPE',
		'JournalLineMod Amount' => 'AMTTYPE',
		'JournalLineMod TaxAmount' => 'AMTTYPE',
		'JournalLineMod Memo' => 'STRTYPE',
		'JournalLineMod EntityRef ListID' => 'IDTYPE',
		'JournalLineMod EntityRef FullName' => 'STRTYPE',
		'JournalLineMod ClassRef ListID' => 'IDTYPE',
		'JournalLineMod ClassRef FullName' => 'STRTYPE',
		'JournalLineMod ItemSalesTaxRef ListID' => 'IDTYPE',
		'JournalLineMod ItemSalesTaxRef FullName' => 'STRTYPE',
		'JournalLineMod BillableStatus' => 'ENUMTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'EditSequence' => 16,
		'RefNumber' => 11,
		'CurrencyRef FullName' => 64,
		'JournalLineMod AccountRef FullName' => 159,
		'JournalLineMod Memo' => 4095,
		'JournalLineMod EntityRef FullName' => 209,
		'JournalLineMod ClassRef FullName' => 159,
		'JournalLineMod ItemSalesTaxRef FullName' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'IsAmountsEnteredInHomeCurrency' => 8.0,
		'CurrencyRef ListID' => 8.0,
		'CurrencyRef FullName' => 8.0,
		'ExchangeRate' => 8.0,
		'JournalLineMod TaxAmount' => 6.1,
		'JournalLineMod ItemSalesTaxRef ListID' => 6.0,
		'JournalLineMod ItemSalesTaxRef FullName' => 6.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'JournalLineMod TaxAmount' => ['US','CA','UK'],
		'JournalLineMod ItemSalesTaxRef ListID' => ['US'],
		'JournalLineMod ItemSalesTaxRef FullName' => ['US'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TxnID',
		'EditSequence',
		'TxnDate',
		'RefNumber',
		'IsAdjustment',
		'IsAmountsEnteredInHomeCurrency',
		'CurrencyRef',
		'CurrencyRef ListID',
		'CurrencyRef FullName',
		'ExchangeRate',
		'JournalLineMod',
		'JournalLineMod TxnLineID',
		'JournalLineMod JournalLineType',
		'JournalLineMod AccountRef ListID',
		'JournalLineMod AccountRef FullName',
		'JournalLineMod Amount',
		'JournalLineMod TaxAmount',
		'JournalLineMod Memo',
		'JournalLineMod EntityRef ListID',
		'JournalLineMod EntityRef FullName',
		'JournalLineMod ClassRef ListID',
		'JournalLineMod ClassRef FullName',
		'JournalLineMod ItemSalesTaxRef ListID',
		'JournalLineMod ItemSalesTaxRef FullName',
		'JournalLineMod BillableStatus',
		'IncludeRetElement',
	];
}
