<?php declare(strict_types=1);

/**
 * Schema object for: LeadModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class LeadModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'LeadMod ListID' => 'IDTYPE',
		'LeadMod EditSequence' => 'STRTYPE',
		'LeadMod FullName' => 'STRTYPE',
		'LeadMod Status' => 'ENUMTYPE',
		'LeadMod CompanyName' => 'STRTYPE',
		'LeadMod MainPhone' => 'STRTYPE',
		'LeadMod AdditionalContactRef ContactName' => 'STRTYPE',
		'LeadMod AdditionalContactRef ContactValue' => 'STRTYPE',
		'LeadMod LocationsMod LocationID' => 'INTTYPE',
		'LeadMod LocationsMod Location' => 'STRTYPE',
		'LeadMod LocationsMod LeadAddress Addr1' => 'STRTYPE',
		'LeadMod LocationsMod LeadAddress Addr2' => 'STRTYPE',
		'LeadMod LocationsMod LeadAddress Addr3' => 'STRTYPE',
		'LeadMod LocationsMod LeadAddress Addr4' => 'STRTYPE',
		'LeadMod LocationsMod LeadAddress Addr5' => 'STRTYPE',
		'LeadMod LeadContactsMod LeadContactID' => 'INTTYPE',
		'LeadMod LeadContactsMod Salutation' => 'STRTYPE',
		'LeadMod LeadContactsMod FirstName' => 'STRTYPE',
		'LeadMod LeadContactsMod MiddleName' => 'STRTYPE',
		'LeadMod LeadContactsMod LastName' => 'STRTYPE',
		'LeadMod LeadContactsMod JobTitle' => 'STRTYPE',
		'LeadMod LeadContactsMod AdditionalContactRef ContactName' => 'STRTYPE',
		'LeadMod LeadContactsMod AdditionalContactRef ContactValue' => 'STRTYPE',
		'LeadMod LeadContactsMod IsPrimaryContact' => 'BOOLTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'LeadMod EditSequence' => 16,
		'LeadMod FullName' => 41,
		'LeadMod CompanyName' => 41,
		'LeadMod MainPhone' => 21,
		'LeadMod AdditionalContactRef ContactName' => 40,
		'LeadMod AdditionalContactRef ContactValue' => 255,
		'LeadMod LocationsMod Location' => 32,
		'LeadMod LocationsMod LeadAddress Addr1' => 41,
		'LeadMod LocationsMod LeadAddress Addr2' => 41,
		'LeadMod LocationsMod LeadAddress Addr3' => 41,
		'LeadMod LocationsMod LeadAddress Addr4' => 41,
		'LeadMod LocationsMod LeadAddress Addr5' => 41,
		'LeadMod LeadContactsMod Salutation' => 15,
		'LeadMod LeadContactsMod FirstName' => 25,
		'LeadMod LeadContactsMod MiddleName' => 5,
		'LeadMod LeadContactsMod LastName' => 25,
		'LeadMod LeadContactsMod JobTitle' => 41,
		'LeadMod LeadContactsMod AdditionalContactRef ContactName' => 40,
		'LeadMod LeadContactsMod AdditionalContactRef ContactValue' => 255,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'LeadMod LocationsMod LeadAddress Addr4' => 2.0,
		'LeadMod LocationsMod LeadAddress Addr5' => 6.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'LeadMod',
		'LeadMod ListID',
		'LeadMod EditSequence',
		'LeadMod FullName',
		'LeadMod Status',
		'LeadMod CompanyName',
		'LeadMod MainPhone',
		'LeadMod AdditionalContactRef ContactName',
		'LeadMod AdditionalContactRef ContactValue',
		'LeadMod LocationsMod LocationID',
		'LeadMod LocationsMod Location',
		'LeadMod LocationsMod LeadAddress Addr1',
		'LeadMod LocationsMod LeadAddress Addr2',
		'LeadMod LocationsMod LeadAddress Addr3',
		'LeadMod LocationsMod LeadAddress Addr4',
		'LeadMod LocationsMod LeadAddress Addr5',
		'LeadMod LeadContactsMod LeadContactID',
		'LeadMod LeadContactsMod Salutation',
		'LeadMod LeadContactsMod FirstName',
		'LeadMod LeadContactsMod MiddleName',
		'LeadMod LeadContactsMod LastName',
		'LeadMod LeadContactsMod JobTitle',
		'LeadMod LeadContactsMod AdditionalContactRef ContactName',
		'LeadMod LeadContactsMod AdditionalContactRef ContactValue',
		'LeadMod LeadContactsMod IsPrimaryContact',
		'IncludeRetElement',
	];
}
