<?php declare(strict_types=1);

/**
 * Schema object for: PriceDiscountAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbposxmlops30.xml file in this package.
 */
final class PriceDiscountAddRq extends AbstractSchemaObject
{
	/**
	 * This QuickBooks Action is found only in the QuickBooks Point of Sale (QBPOS) sdk.
	 * @var bool
	 */
	protected $_isQbxmlPosOnly = true;

	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'PriceDiscountAdd PriceDiscountName' => 'STRTYPE',
		'PriceDiscountAdd PriceDiscountReason' => 'STRTYPE',
		'PriceDiscountAdd Comments' => 'STRTYPE',
		'PriceDiscountAdd Associate' => 'STRTYPE',
		'PriceDiscountAdd PriceDiscountType' => 'ENUMTYPE',
		'PriceDiscountAdd IsInactive' => 'BOOLTYPE',
		'PriceDiscountAdd PriceDiscountPriceLevels' => 'STRTYPE',
		'PriceDiscountAdd PriceDiscountXValue' => 'INTTYPE',
		'PriceDiscountAdd PriceDiscountYValue' => 'FLOATTYPE',
		'PriceDiscountAdd IsApplicableOverXValue' => 'BOOLTYPE',
		'PriceDiscountAdd StartDate' => 'DATETIMETYPE',
		'PriceDiscountAdd StopDate' => 'DATETIMETYPE',
		'PriceDiscountAdd PriceDiscountItemAdd ListID' => 'IDTYPE',
		'PriceDiscountAdd PriceDiscountItemAdd UnitOfMeasure' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'PriceDiscountAdd PriceDiscountName' => 200,
		'PriceDiscountAdd PriceDiscountReason' => 30,
		'PriceDiscountAdd Comments' => 300,
		'PriceDiscountAdd Associate' => 40,
		'PriceDiscountAdd PriceDiscountPriceLevels' => 12,
		'PriceDiscountAdd PriceDiscountItemAdd UnitOfMeasure' => 20,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'IncludeRetElement' => 2.5,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'PriceDiscountAdd',
		'PriceDiscountAdd PriceDiscountName',
		'PriceDiscountAdd PriceDiscountReason',
		'PriceDiscountAdd Comments',
		'PriceDiscountAdd Associate',
		'PriceDiscountAdd PriceDiscountType',
		'PriceDiscountAdd IsInactive',
		'PriceDiscountAdd PriceDiscountPriceLevels',
		'PriceDiscountAdd PriceDiscountXValue',
		'PriceDiscountAdd PriceDiscountYValue',
		'PriceDiscountAdd IsApplicableOverXValue',
		'PriceDiscountAdd StartDate',
		'PriceDiscountAdd StopDate',
		'PriceDiscountAdd PriceDiscountItemAdd ListID',
		'PriceDiscountAdd PriceDiscountItemAdd UnitOfMeasure',
		'IncludeRetElement',
	];
}
