<?php declare(strict_types=1);

/**
 * Schema object for: PriceLevelAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class PriceLevelAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = 'PriceLevelAdd';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'Name' => 'STRTYPE',
			'IsActive' => 'BOOLTYPE',
			'PriceLevelFixedPercentage' => 'PERCENTTYPE',
			'PriceLevelPerItem ItemRef ListID' => 'IDTYPE',
			'PriceLevelPerItem ItemRef FullName' => 'STRTYPE',
			'PriceLevelPerItem CustomPrice' => 'PRICETYPE',
			'PriceLevelPerItem CustomPricePercent' => 'PERCENTTYPE',
			'PriceLevelPerItem AdjustPercentage' => 'PERCENTTYPE',
			'PriceLevelPerItem AdjustRelativeTo' => 'ENUMTYPE',
			'CurrencyRef ListID' => 'IDTYPE',
			'CurrencyRef FullName' => 'STRTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'Name' => 31,
			'IsActive' => 0,
			'PriceLevelFixedPercentage' => 0,
			'PriceLevelPerItem ItemRef ListID' => 0,
			'PriceLevelPerItem ItemRef FullName' => 0,
			'PriceLevelPerItem CustomPrice' => 0,
			'PriceLevelPerItem CustomPricePercent' => 0,
			'PriceLevelPerItem AdjustPercentage' => 0,
			'PriceLevelPerItem AdjustRelativeTo' => 0,
			'CurrencyRef ListID' => 0,
			'CurrencyRef FullName' => 0,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'Name' => 999.99,
			'IsActive' => 999.99,
			'PriceLevelFixedPercentage' => 999.99,
			'PriceLevelPerItem ItemRef ListID' => 999.99,
			'PriceLevelPerItem ItemRef FullName' => 999.99,
			'PriceLevelPerItem CustomPrice' => 999.99,
			'PriceLevelPerItem CustomPricePercent' => 999.99,
			'PriceLevelPerItem AdjustPercentage' => 999.99,
			'PriceLevelPerItem AdjustRelativeTo' => 999.99,
			'CurrencyRef ListID' => 999.99,
			'CurrencyRef FullName' => 999.99,
			'IncludeRetElement' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'Name' => false,
			'IsActive' => false,
			'PriceLevelFixedPercentage' => false,
			'PriceLevelPerItem ItemRef ListID' => false,
			'PriceLevelPerItem ItemRef FullName' => false,
			'PriceLevelPerItem CustomPrice' => false,
			'PriceLevelPerItem CustomPricePercent' => false,
			'PriceLevelPerItem AdjustPercentage' => false,
			'PriceLevelPerItem AdjustRelativeTo' => false,
			'CurrencyRef ListID' => false,
			'CurrencyRef FullName' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'Name',
			'IsActive',
			'PriceLevelFixedPercentage',
			'PriceLevelPerItem',
			'PriceLevelPerItem ItemRef',
			'PriceLevelPerItem ItemRef ListID',
			'PriceLevelPerItem ItemRef FullName',
			'PriceLevelPerItem CustomPrice',
			'PriceLevelPerItem CustomPricePercent',
			'PriceLevelPerItem AdjustPercentage',
			'PriceLevelPerItem AdjustRelativeTo',
			'CurrencyRef',
			'CurrencyRef ListID',
			'CurrencyRef FullName',
			'IncludeRetElement',
		];

		return $paths;
	}
}
