<?php declare(strict_types=1);

/**
 * Schema object for: PurchaseOrderAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class PurchaseOrderAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'PurchaseOrderAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'VendorRef ListID' => 'IDTYPE',
		'VendorRef FullName' => 'STRTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'InventorySiteRef ListID' => 'IDTYPE',
		'InventorySiteRef FullName' => 'STRTYPE',
		'ShipToEntityRef ListID' => 'IDTYPE',
		'ShipToEntityRef FullName' => 'STRTYPE',
		'TemplateRef ListID' => 'IDTYPE',
		'TemplateRef FullName' => 'STRTYPE',
		'TxnDate' => 'DATETYPE',
		'RefNumber' => 'STRTYPE',
		'VendorAddress Addr1' => 'STRTYPE',
		'VendorAddress Addr2' => 'STRTYPE',
		'VendorAddress Addr3' => 'STRTYPE',
		'VendorAddress Addr4' => 'STRTYPE',
		'VendorAddress Addr5' => 'STRTYPE',
		'VendorAddress City' => 'STRTYPE',
		'VendorAddress State' => 'STRTYPE',
		'VendorAddress PostalCode' => 'STRTYPE',
		'VendorAddress Country' => 'STRTYPE',
		'VendorAddress Note' => 'STRTYPE',
		'ShipAddress Addr1' => 'STRTYPE',
		'ShipAddress Addr2' => 'STRTYPE',
		'ShipAddress Addr3' => 'STRTYPE',
		'ShipAddress Addr4' => 'STRTYPE',
		'ShipAddress Addr5' => 'STRTYPE',
		'ShipAddress City' => 'STRTYPE',
		'ShipAddress State' => 'STRTYPE',
		'ShipAddress PostalCode' => 'STRTYPE',
		'ShipAddress Country' => 'STRTYPE',
		'ShipAddress Note' => 'STRTYPE',
		'TermsRef ListID' => 'IDTYPE',
		'TermsRef FullName' => 'STRTYPE',
		'DueDate' => 'DATETYPE',
		'ExpectedDate' => 'DATETYPE',
		'ShipMethodRef ListID' => 'IDTYPE',
		'ShipMethodRef FullName' => 'STRTYPE',
		'FOB' => 'STRTYPE',
		'Memo' => 'STRTYPE',
		'VendorMsg' => 'STRTYPE',
		'IsToBePrinted' => 'BOOLTYPE',
		'IsToBeEmailed' => 'BOOLTYPE',
		'IsTaxIncluded' => 'BOOLTYPE',
		'SalesTaxCodeRef ListID' => 'IDTYPE',
		'SalesTaxCodeRef FullName' => 'STRTYPE',
		'Other1' => 'STRTYPE',
		'Other2' => 'STRTYPE',
		'ExchangeRate' => 'FLOATTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'PurchaseOrderLineAdd ItemRef ListID' => 'IDTYPE',
		'PurchaseOrderLineAdd ItemRef FullName' => 'STRTYPE',
		'PurchaseOrderLineAdd ManufacturerPartNumber' => 'STRTYPE',
		'PurchaseOrderLineAdd Desc' => 'STRTYPE',
		'PurchaseOrderLineAdd Quantity' => 'QUANTYPE',
		'PurchaseOrderLineAdd UnitOfMeasure' => 'STRTYPE',
		'PurchaseOrderLineAdd Rate' => 'PRICETYPE',
		'PurchaseOrderLineAdd ClassRef ListID' => 'IDTYPE',
		'PurchaseOrderLineAdd ClassRef FullName' => 'STRTYPE',
		'PurchaseOrderLineAdd Amount' => 'AMTTYPE',
		'PurchaseOrderLineAdd TaxAmount' => 'AMTTYPE',
		'PurchaseOrderLineAdd InventorySiteLocationRef ListID' => 'IDTYPE',
		'PurchaseOrderLineAdd InventorySiteLocationRef FullName' => 'STRTYPE',
		'PurchaseOrderLineAdd CustomerRef ListID' => 'IDTYPE',
		'PurchaseOrderLineAdd CustomerRef FullName' => 'STRTYPE',
		'PurchaseOrderLineAdd ServiceDate' => 'DATETYPE',
		'PurchaseOrderLineAdd SalesTaxCodeRef ListID' => 'IDTYPE',
		'PurchaseOrderLineAdd SalesTaxCodeRef FullName' => 'STRTYPE',
		'PurchaseOrderLineAdd OverrideItemAccountRef ListID' => 'IDTYPE',
		'PurchaseOrderLineAdd OverrideItemAccountRef FullName' => 'STRTYPE',
		'PurchaseOrderLineAdd Other1' => 'STRTYPE',
		'PurchaseOrderLineAdd Other2' => 'STRTYPE',
		'PurchaseOrderLineAdd DataExt OwnerID' => 'GUIDTYPE',
		'PurchaseOrderLineAdd DataExt DataExtName' => 'STRTYPE',
		'PurchaseOrderLineAdd DataExt DataExtValue' => 'STRTYPE',
		'PurchaseOrderLineGroupAdd ItemGroupRef ListID' => 'IDTYPE',
		'PurchaseOrderLineGroupAdd ItemGroupRef FullName' => 'STRTYPE',
		'PurchaseOrderLineGroupAdd Desc' => 'STRTYPE',
		'PurchaseOrderLineGroupAdd Quantity' => 'QUANTYPE',
		'PurchaseOrderLineGroupAdd UnitOfMeasure' => 'STRTYPE',
		'PurchaseOrderLineGroupAdd ServiceDate' => 'DATETYPE',
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef ListID' => 'IDTYPE',
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef FullName' => 'STRTYPE',
		'PurchaseOrderLineGroupAdd DataExt OwnerID' => 'GUIDTYPE',
		'PurchaseOrderLineGroupAdd DataExt DataExtName' => 'STRTYPE',
		'PurchaseOrderLineGroupAdd DataExt DataExtValue' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'VendorRef FullName' => 41,
		'ClassRef FullName' => 159,
		'InventorySiteRef FullName' => 31,
		'ShipToEntityRef FullName' => 209,
		'TemplateRef FullName' => 31,
		'RefNumber' => 11,
		'VendorAddress Addr1' => 41,
		'VendorAddress Addr2' => 41,
		'VendorAddress Addr3' => 41,
		'VendorAddress Addr4' => 41,
		'VendorAddress Addr5' => 41,
		'VendorAddress City' => 31,
		'VendorAddress State' => 21,
		'VendorAddress PostalCode' => 13,
		'VendorAddress Country' => 31,
		'VendorAddress Note' => 41,
		'ShipAddress Addr1' => 41,
		'ShipAddress Addr2' => 41,
		'ShipAddress Addr3' => 41,
		'ShipAddress Addr4' => 41,
		'ShipAddress Addr5' => 41,
		'ShipAddress City' => 31,
		'ShipAddress State' => 21,
		'ShipAddress PostalCode' => 13,
		'ShipAddress Country' => 31,
		'ShipAddress Note' => 41,
		'TermsRef FullName' => 31,
		'ShipMethodRef FullName' => 15,
		'FOB' => 13,
		'Memo' => 4095,
		'VendorMsg' => 99,
		'SalesTaxCodeRef FullName' => 3,
		'Other1' => 25,
		'Other2' => 29,
		'PurchaseOrderLineAdd ManufacturerPartNumber' => 31,
		'PurchaseOrderLineAdd Desc' => 4095,
		'PurchaseOrderLineAdd UnitOfMeasure' => 31,
		'PurchaseOrderLineAdd ClassRef FullName' => 159,
		'PurchaseOrderLineAdd InventorySiteLocationRef FullName' => 31,
		'PurchaseOrderLineAdd CustomerRef FullName' => 209,
		'PurchaseOrderLineAdd SalesTaxCodeRef FullName' => 3,
		'PurchaseOrderLineAdd OverrideItemAccountRef FullName' => 159,
		'PurchaseOrderLineAdd Other1' => 29,
		'PurchaseOrderLineAdd Other2' => 29,
		'PurchaseOrderLineAdd DataExt DataExtName' => 31,
		'PurchaseOrderLineGroupAdd ItemGroupRef FullName' => 31,
		'PurchaseOrderLineGroupAdd UnitOfMeasure' => 31,
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef FullName' => 31,
		'PurchaseOrderLineGroupAdd DataExt DataExtName' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'InventorySiteRef ListID' => 10.0,
		'InventorySiteRef FullName' => 10.0,
		'TemplateRef ListID' => 3.0,
		'TemplateRef FullName' => 3.0,
		'VendorAddress Addr4' => 2.0,
		'VendorAddress Addr5' => 6.0,
		'VendorAddress Note' => 6.0,
		'ShipAddress Addr4' => 2.0,
		'ShipAddress Addr5' => 6.0,
		'ShipAddress Note' => 6.0,
		'IsToBeEmailed' => 6.0,
		'IsTaxIncluded' => 6.0,
		'SalesTaxCodeRef ListID' => 6.0,
		'SalesTaxCodeRef FullName' => 6.0,
		'Other1' => 6.0,
		'Other2' => 6.0,
		'ExchangeRate' => 8.0,
		'ExternalGUID' => 9.0,
		'PurchaseOrderLineAdd ManufacturerPartNumber' => 7.0,
		'PurchaseOrderLineAdd UnitOfMeasure' => 7.0,
		'PurchaseOrderLineAdd TaxAmount' => 6.1,
		'PurchaseOrderLineAdd InventorySiteLocationRef ListID' => 12.0,
		'PurchaseOrderLineAdd InventorySiteLocationRef FullName' => 12.0,
		'PurchaseOrderLineAdd SalesTaxCodeRef ListID' => 6.0,
		'PurchaseOrderLineAdd SalesTaxCodeRef FullName' => 6.0,
		'PurchaseOrderLineAdd OverrideItemAccountRef ListID' => 2.0,
		'PurchaseOrderLineAdd OverrideItemAccountRef FullName' => 2.0,
		'PurchaseOrderLineAdd Other1' => 6.0,
		'PurchaseOrderLineAdd Other2' => 6.0,
		'PurchaseOrderLineAdd DataExt OwnerID' => 5.0,
		'PurchaseOrderLineAdd DataExt DataExtName' => 5.0,
		'PurchaseOrderLineAdd DataExt DataExtValue' => 5.0,
		'PurchaseOrderLineGroupAdd UnitOfMeasure' => 7.0,
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef ListID' => 12.0,
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef FullName' => 12.0,
		'PurchaseOrderLineGroupAdd DataExt OwnerID' => 5.0,
		'PurchaseOrderLineGroupAdd DataExt DataExtName' => 5.0,
		'PurchaseOrderLineGroupAdd DataExt DataExtValue' => 5.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'InventorySiteRef ListID' => ['AU'],
		'InventorySiteRef FullName' => ['AU'],
		'IsTaxIncluded' => ['US'],
		'SalesTaxCodeRef ListID' => ['US'],
		'SalesTaxCodeRef FullName' => ['US'],
		'PurchaseOrderLineAdd TaxAmount' => ['US','CA','UK'],
		'PurchaseOrderLineAdd InventorySiteLocationRef ListID' => ['AU'],
		'PurchaseOrderLineAdd InventorySiteLocationRef FullName' => ['AU'],
		'PurchaseOrderLineAdd SalesTaxCodeRef ListID' => ['US'],
		'PurchaseOrderLineAdd SalesTaxCodeRef FullName' => ['US'],
		'PurchaseOrderLineGroupAdd Desc' => ['US','CA','UK','AU'],
		'PurchaseOrderLineGroupAdd ServiceDate' => ['US','CA','UK','AU'],
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef ListID' => ['AU'],
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef FullName' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'VendorRef',
		'VendorRef ListID',
		'VendorRef FullName',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'InventorySiteRef',
		'InventorySiteRef ListID',
		'InventorySiteRef FullName',
		'ShipToEntityRef',
		'ShipToEntityRef ListID',
		'ShipToEntityRef FullName',
		'TemplateRef',
		'TemplateRef ListID',
		'TemplateRef FullName',
		'TxnDate',
		'RefNumber',
		'VendorAddress',
		'VendorAddress Addr1',
		'VendorAddress Addr2',
		'VendorAddress Addr3',
		'VendorAddress Addr4',
		'VendorAddress Addr5',
		'VendorAddress City',
		'VendorAddress State',
		'VendorAddress PostalCode',
		'VendorAddress Country',
		'VendorAddress Note',
		'ShipAddress',
		'ShipAddress Addr1',
		'ShipAddress Addr2',
		'ShipAddress Addr3',
		'ShipAddress Addr4',
		'ShipAddress Addr5',
		'ShipAddress City',
		'ShipAddress State',
		'ShipAddress PostalCode',
		'ShipAddress Country',
		'ShipAddress Note',
		'TermsRef',
		'TermsRef ListID',
		'TermsRef FullName',
		'DueDate',
		'ExpectedDate',
		'ShipMethodRef',
		'ShipMethodRef ListID',
		'ShipMethodRef FullName',
		'FOB',
		'Memo',
		'VendorMsg',
		'IsToBePrinted',
		'IsToBeEmailed',
		'IsTaxIncluded',
		'SalesTaxCodeRef',
		'SalesTaxCodeRef ListID',
		'SalesTaxCodeRef FullName',
		'Other1',
		'Other2',
		'ExchangeRate',
		'ExternalGUID',
		'PurchaseOrderLineAdd',
		'PurchaseOrderLineAdd ItemRef',
		'PurchaseOrderLineAdd ItemRef ListID',
		'PurchaseOrderLineAdd ItemRef FullName',
		'PurchaseOrderLineAdd ManufacturerPartNumber',
		'PurchaseOrderLineAdd Desc',
		'PurchaseOrderLineAdd Quantity',
		'PurchaseOrderLineAdd UnitOfMeasure',
		'PurchaseOrderLineAdd Rate',
		'PurchaseOrderLineAdd ClassRef ListID',
		'PurchaseOrderLineAdd ClassRef FullName',
		'PurchaseOrderLineAdd Amount',
		'PurchaseOrderLineAdd TaxAmount',
		'PurchaseOrderLineAdd InventorySiteLocationRef ListID',
		'PurchaseOrderLineAdd InventorySiteLocationRef FullName',
		'PurchaseOrderLineAdd CustomerRef ListID',
		'PurchaseOrderLineAdd CustomerRef FullName',
		'PurchaseOrderLineAdd ServiceDate',
		'PurchaseOrderLineAdd SalesTaxCodeRef ListID',
		'PurchaseOrderLineAdd SalesTaxCodeRef FullName',
		'PurchaseOrderLineAdd OverrideItemAccountRef ListID',
		'PurchaseOrderLineAdd OverrideItemAccountRef FullName',
		'PurchaseOrderLineAdd Other1',
		'PurchaseOrderLineAdd Other2',
		'PurchaseOrderLineAdd DataExt OwnerID',
		'PurchaseOrderLineAdd DataExt DataExtName',
		'PurchaseOrderLineAdd DataExt DataExtValue',
		'PurchaseOrderLineGroupAdd',
		'PurchaseOrderLineGroupAdd ItemGroupRef ListID',
		'PurchaseOrderLineGroupAdd ItemGroupRef FullName',
		'PurchaseOrderLineGroupAdd Desc',
		'PurchaseOrderLineGroupAdd Quantity',
		'PurchaseOrderLineGroupAdd UnitOfMeasure',
		'PurchaseOrderLineGroupAdd ServiceDate',
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef ListID',
		'PurchaseOrderLineGroupAdd InventorySiteLocationRef FullName',
		'PurchaseOrderLineGroupAdd DataExt OwnerID',
		'PurchaseOrderLineGroupAdd DataExt DataExtName',
		'PurchaseOrderLineGroupAdd DataExt DataExtValue',
		'IncludeRetElement',
	];
}
