<?php declare(strict_types=1);

/**
 * Schema object for: SalesOrderAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class SalesOrderAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'SalesOrderAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'CustomerRef ListID' => 'IDTYPE',
		'CustomerRef FullName' => 'STRTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'TemplateRef ListID' => 'IDTYPE',
		'TemplateRef FullName' => 'STRTYPE',
		'TxnDate' => 'DATETYPE',
		'RefNumber' => 'STRTYPE',
		'BillAddress Addr1' => 'STRTYPE',
		'BillAddress Addr2' => 'STRTYPE',
		'BillAddress Addr3' => 'STRTYPE',
		'BillAddress Addr4' => 'STRTYPE',
		'BillAddress Addr5' => 'STRTYPE',
		'BillAddress City' => 'STRTYPE',
		'BillAddress State' => 'STRTYPE',
		'BillAddress PostalCode' => 'STRTYPE',
		'BillAddress Country' => 'STRTYPE',
		'BillAddress Note' => 'STRTYPE',
		'ShipAddress Addr1' => 'STRTYPE',
		'ShipAddress Addr2' => 'STRTYPE',
		'ShipAddress Addr3' => 'STRTYPE',
		'ShipAddress Addr4' => 'STRTYPE',
		'ShipAddress Addr5' => 'STRTYPE',
		'ShipAddress City' => 'STRTYPE',
		'ShipAddress State' => 'STRTYPE',
		'ShipAddress PostalCode' => 'STRTYPE',
		'ShipAddress Country' => 'STRTYPE',
		'ShipAddress Note' => 'STRTYPE',
		'PONumber' => 'STRTYPE',
		'TermsRef ListID' => 'IDTYPE',
		'TermsRef FullName' => 'STRTYPE',
		'DueDate' => 'DATETYPE',
		'SalesRepRef ListID' => 'IDTYPE',
		'SalesRepRef FullName' => 'STRTYPE',
		'FOB' => 'STRTYPE',
		'ShipDate' => 'DATETYPE',
		'ShipMethodRef ListID' => 'IDTYPE',
		'ShipMethodRef FullName' => 'STRTYPE',
		'ItemSalesTaxRef ListID' => 'IDTYPE',
		'ItemSalesTaxRef FullName' => 'STRTYPE',
		'IsManuallyClosed' => 'BOOLTYPE',
		'Memo' => 'STRTYPE',
		'CustomerMsgRef ListID' => 'IDTYPE',
		'CustomerMsgRef FullName' => 'STRTYPE',
		'IsToBePrinted' => 'BOOLTYPE',
		'IsToBeEmailed' => 'BOOLTYPE',
		'IsTaxIncluded' => 'BOOLTYPE',
		'CustomerSalesTaxCodeRef ListID' => 'IDTYPE',
		'CustomerSalesTaxCodeRef FullName' => 'STRTYPE',
		'Other' => 'STRTYPE',
		'ExchangeRate' => 'FLOATTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'SalesOrderLineAdd ItemRef ListID' => 'IDTYPE',
		'SalesOrderLineAdd ItemRef FullName' => 'STRTYPE',
		'SalesOrderLineAdd Desc' => 'STRTYPE',
		'SalesOrderLineAdd Quantity' => 'QUANTYPE',
		'SalesOrderLineAdd UnitOfMeasure' => 'STRTYPE',
		'SalesOrderLineAdd Rate' => 'PRICETYPE',
		'SalesOrderLineAdd RatePercent' => 'PERCENTTYPE',
		'SalesOrderLineAdd PriceLevelRef ListID' => 'IDTYPE',
		'SalesOrderLineAdd PriceLevelRef FullName' => 'STRTYPE',
		'SalesOrderLineAdd ClassRef ListID' => 'IDTYPE',
		'SalesOrderLineAdd ClassRef FullName' => 'STRTYPE',
		'SalesOrderLineAdd Amount' => 'AMTTYPE',
		'SalesOrderLineAdd TaxAmount' => 'AMTTYPE',
		'SalesOrderLineAdd OptionForPriceRuleConflict' => 'ENUMTYPE',
		'SalesOrderLineAdd InventorySiteRef ListID' => 'IDTYPE',
		'SalesOrderLineAdd InventorySiteRef FullName' => 'STRTYPE',
		'SalesOrderLineAdd InventorySiteLocationRef ListID' => 'IDTYPE',
		'SalesOrderLineAdd InventorySiteLocationRef FullName' => 'STRTYPE',
		'SalesOrderLineAdd SerialNumber' => 'STRTYPE',
		'SalesOrderLineAdd LotNumber' => 'STRTYPE',
		'SalesOrderLineAdd SalesTaxCodeRef ListID' => 'IDTYPE',
		'SalesOrderLineAdd SalesTaxCodeRef FullName' => 'STRTYPE',
		'SalesOrderLineAdd IsManuallyClosed' => 'BOOLTYPE',
		'SalesOrderLineAdd Other1' => 'STRTYPE',
		'SalesOrderLineAdd Other2' => 'STRTYPE',
		'SalesOrderLineAdd DataExt OwnerID' => 'GUIDTYPE',
		'SalesOrderLineAdd DataExt DataExtName' => 'STRTYPE',
		'SalesOrderLineAdd DataExt DataExtValue' => 'STRTYPE',
		'SalesOrderLineGroupAdd ItemGroupRef ListID' => 'IDTYPE',
		'SalesOrderLineGroupAdd ItemGroupRef FullName' => 'STRTYPE',
		'SalesOrderLineGroupAdd Desc' => 'STRTYPE',
		'SalesOrderLineGroupAdd Quantity' => 'QUANTYPE',
		'SalesOrderLineGroupAdd UnitOfMeasure' => 'STRTYPE',
		'SalesOrderLineGroupAdd InventorySiteRef ListID' => 'IDTYPE',
		'SalesOrderLineGroupAdd InventorySiteRef FullName' => 'STRTYPE',
		'SalesOrderLineGroupAdd InventorySiteLocationRef ListID' => 'IDTYPE',
		'SalesOrderLineGroupAdd InventorySiteLocationRef FullName' => 'STRTYPE',
		'SalesOrderLineGroupAdd DataExt OwnerID' => 'GUIDTYPE',
		'SalesOrderLineGroupAdd DataExt DataExtName' => 'STRTYPE',
		'SalesOrderLineGroupAdd DataExt DataExtValue' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'CustomerRef FullName' => 209,
		'ClassRef FullName' => 159,
		'TemplateRef FullName' => 31,
		'RefNumber' => 11,
		'BillAddress Addr1' => 41,
		'BillAddress Addr2' => 41,
		'BillAddress Addr3' => 41,
		'BillAddress Addr4' => 41,
		'BillAddress Addr5' => 41,
		'BillAddress City' => 31,
		'BillAddress State' => 21,
		'BillAddress PostalCode' => 13,
		'BillAddress Country' => 31,
		'BillAddress Note' => 41,
		'ShipAddress Addr1' => 41,
		'ShipAddress Addr2' => 41,
		'ShipAddress Addr3' => 41,
		'ShipAddress Addr4' => 41,
		'ShipAddress Addr5' => 41,
		'ShipAddress City' => 31,
		'ShipAddress State' => 21,
		'ShipAddress PostalCode' => 13,
		'ShipAddress Country' => 31,
		'ShipAddress Note' => 41,
		'PONumber' => 25,
		'TermsRef FullName' => 31,
		'SalesRepRef FullName' => 5,
		'FOB' => 13,
		'ShipMethodRef FullName' => 15,
		'ItemSalesTaxRef FullName' => 31,
		'Memo' => 4095,
		'CustomerMsgRef FullName' => 101,
		'CustomerSalesTaxCodeRef FullName' => 3,
		'Other' => 29,
		'SalesOrderLineAdd Desc' => 4095,
		'SalesOrderLineAdd UnitOfMeasure' => 31,
		'SalesOrderLineAdd PriceLevelRef FullName' => 31,
		'SalesOrderLineAdd ClassRef FullName' => 159,
		'SalesOrderLineAdd InventorySiteRef FullName' => 31,
		'SalesOrderLineAdd InventorySiteLocationRef FullName' => 31,
		'SalesOrderLineAdd SerialNumber' => 4095,
		'SalesOrderLineAdd LotNumber' => 40,
		'SalesOrderLineAdd SalesTaxCodeRef FullName' => 3,
		'SalesOrderLineAdd Other1' => 29,
		'SalesOrderLineAdd Other2' => 29,
		'SalesOrderLineAdd DataExt DataExtName' => 31,
		'SalesOrderLineGroupAdd ItemGroupRef FullName' => 31,
		'SalesOrderLineGroupAdd UnitOfMeasure' => 31,
		'SalesOrderLineGroupAdd InventorySiteRef FullName' => 31,
		'SalesOrderLineGroupAdd InventorySiteLocationRef FullName' => 31,
		'SalesOrderLineGroupAdd DataExt DataExtName' => 31,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'TemplateRef ListID' => 3.0,
		'TemplateRef FullName' => 3.0,
		'BillAddress Addr4' => 2.0,
		'BillAddress Addr5' => 6.0,
		'BillAddress Note' => 6.0,
		'ShipAddress Addr4' => 2.0,
		'ShipAddress Addr5' => 6.0,
		'ShipAddress Note' => 6.0,
		'IsToBeEmailed' => 6.0,
		'IsTaxIncluded' => 6.0,
		'Other' => 6.0,
		'ExchangeRate' => 8.0,
		'ExternalGUID' => 9.0,
		'SalesOrderLineAdd UnitOfMeasure' => 7.0,
		'SalesOrderLineAdd PriceLevelRef ListID' => 4.0,
		'SalesOrderLineAdd PriceLevelRef FullName' => 4.0,
		'SalesOrderLineAdd TaxAmount' => 6.1,
		'SalesOrderLineAdd OptionForPriceRuleConflict' => 13.0,
		'SalesOrderLineAdd InventorySiteRef ListID' => 10.0,
		'SalesOrderLineAdd InventorySiteRef FullName' => 10.0,
		'SalesOrderLineAdd InventorySiteLocationRef ListID' => 12.0,
		'SalesOrderLineAdd InventorySiteLocationRef FullName' => 12.0,
		'SalesOrderLineAdd Other1' => 6.0,
		'SalesOrderLineAdd Other2' => 6.0,
		'SalesOrderLineAdd DataExt OwnerID' => 5.0,
		'SalesOrderLineAdd DataExt DataExtName' => 5.0,
		'SalesOrderLineAdd DataExt DataExtValue' => 5.0,
		'SalesOrderLineGroupAdd UnitOfMeasure' => 7.0,
		'SalesOrderLineGroupAdd InventorySiteRef ListID' => 10.0,
		'SalesOrderLineGroupAdd InventorySiteRef FullName' => 10.0,
		'SalesOrderLineGroupAdd InventorySiteLocationRef ListID' => 12.0,
		'SalesOrderLineGroupAdd InventorySiteLocationRef FullName' => 12.0,
		'SalesOrderLineGroupAdd DataExt OwnerID' => 5.0,
		'SalesOrderLineGroupAdd DataExt DataExtName' => 5.0,
		'SalesOrderLineGroupAdd DataExt DataExtValue' => 5.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'IsTaxIncluded' => ['US'],
		'SalesOrderLineAdd TaxAmount' => ['US','CA','UK'],
		'SalesOrderLineAdd InventorySiteRef ListID' => ['AU'],
		'SalesOrderLineAdd InventorySiteRef FullName' => ['AU'],
		'SalesOrderLineAdd InventorySiteLocationRef ListID' => ['AU'],
		'SalesOrderLineAdd InventorySiteLocationRef FullName' => ['AU'],
		'SalesOrderLineAdd SerialNumber' => ['AU'],
		'SalesOrderLineAdd LotNumber' => ['AU'],
		'SalesOrderLineGroupAdd Desc' => ['US','CA','UK','AU'],
		'SalesOrderLineGroupAdd InventorySiteRef ListID' => ['AU'],
		'SalesOrderLineGroupAdd InventorySiteRef FullName' => ['AU'],
		'SalesOrderLineGroupAdd InventorySiteLocationRef ListID' => ['AU'],
		'SalesOrderLineGroupAdd InventorySiteLocationRef FullName' => ['AU'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'CustomerRef',
		'CustomerRef ListID',
		'CustomerRef FullName',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'TemplateRef',
		'TemplateRef ListID',
		'TemplateRef FullName',
		'TxnDate',
		'RefNumber',
		'BillAddress',
		'BillAddress Addr1',
		'BillAddress Addr2',
		'BillAddress Addr3',
		'BillAddress Addr4',
		'BillAddress Addr5',
		'BillAddress City',
		'BillAddress State',
		'BillAddress PostalCode',
		'BillAddress Country',
		'BillAddress Note',
		'ShipAddress',
		'ShipAddress Addr1',
		'ShipAddress Addr2',
		'ShipAddress Addr3',
		'ShipAddress Addr4',
		'ShipAddress Addr5',
		'ShipAddress City',
		'ShipAddress State',
		'ShipAddress PostalCode',
		'ShipAddress Country',
		'ShipAddress Note',
		'PONumber',
		'TermsRef',
		'TermsRef ListID',
		'TermsRef FullName',
		'DueDate',
		'SalesRepRef',
		'SalesRepRef ListID',
		'SalesRepRef FullName',
		'FOB',
		'ShipDate',
		'ShipMethodRef',
		'ShipMethodRef ListID',
		'ShipMethodRef FullName',
		'ItemSalesTaxRef',
		'ItemSalesTaxRef ListID',
		'ItemSalesTaxRef FullName',
		'IsManuallyClosed',
		'Memo',
		'CustomerMsgRef',
		'CustomerMsgRef ListID',
		'CustomerMsgRef FullName',
		'IsToBePrinted',
		'IsToBeEmailed',
		'IsTaxIncluded',
		'CustomerSalesTaxCodeRef',
		'CustomerSalesTaxCodeRef ListID',
		'CustomerSalesTaxCodeRef FullName',
		'Other',
		'ExchangeRate',
		'ExternalGUID',
		'SalesOrderLineAdd',
		'SalesOrderLineAdd ItemRef',
		'SalesOrderLineAdd ItemRef ListID',
		'SalesOrderLineAdd ItemRef FullName',
		'SalesOrderLineAdd Desc',
		'SalesOrderLineAdd Quantity',
		'SalesOrderLineAdd UnitOfMeasure',
		'SalesOrderLineAdd Rate',
		'SalesOrderLineAdd RatePercent',
		'SalesOrderLineAdd PriceLevelRef ListID',
		'SalesOrderLineAdd PriceLevelRef FullName',
		'SalesOrderLineAdd ClassRef ListID',
		'SalesOrderLineAdd ClassRef FullName',
		'SalesOrderLineAdd Amount',
		'SalesOrderLineAdd TaxAmount',
		'SalesOrderLineAdd OptionForPriceRuleConflict',
		'SalesOrderLineAdd InventorySiteRef ListID',
		'SalesOrderLineAdd InventorySiteRef FullName',
		'SalesOrderLineAdd InventorySiteLocationRef ListID',
		'SalesOrderLineAdd InventorySiteLocationRef FullName',
		'SalesOrderLineAdd SerialNumber',
		'SalesOrderLineAdd LotNumber',
		'SalesOrderLineAdd SalesTaxCodeRef ListID',
		'SalesOrderLineAdd SalesTaxCodeRef FullName',
		'SalesOrderLineAdd IsManuallyClosed',
		'SalesOrderLineAdd Other1',
		'SalesOrderLineAdd Other2',
		'SalesOrderLineAdd DataExt OwnerID',
		'SalesOrderLineAdd DataExt DataExtName',
		'SalesOrderLineAdd DataExt DataExtValue',
		'SalesOrderLineGroupAdd',
		'SalesOrderLineGroupAdd ItemGroupRef ListID',
		'SalesOrderLineGroupAdd ItemGroupRef FullName',
		'SalesOrderLineGroupAdd Desc',
		'SalesOrderLineGroupAdd Quantity',
		'SalesOrderLineGroupAdd UnitOfMeasure',
		'SalesOrderLineGroupAdd InventorySiteRef ListID',
		'SalesOrderLineGroupAdd InventorySiteRef FullName',
		'SalesOrderLineGroupAdd InventorySiteLocationRef ListID',
		'SalesOrderLineGroupAdd InventorySiteLocationRef FullName',
		'SalesOrderLineGroupAdd DataExt OwnerID',
		'SalesOrderLineGroupAdd DataExt DataExtName',
		'SalesOrderLineGroupAdd DataExt DataExtValue',
		'IncludeRetElement',
	];
}
