<?php declare(strict_types=1);

/**
 * Schema object for: SalesTaxCodeAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class SalesTaxCodeAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = 'SalesTaxCodeAdd';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'Name' => 'STRTYPE',
			'IsActive' => 'BOOLTYPE',
			'IsTaxable' => 'BOOLTYPE',
			'Desc' => 'STRTYPE',
			'ItemPurchaseTaxRef ListID' => 'IDTYPE',
			'ItemPurchaseTaxRef FullName' => 'STRTYPE',
			'ItemSalesTaxRef ListID' => 'IDTYPE',
			'ItemSalesTaxRef FullName' => 'STRTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'Name' => 3,
			'IsActive' => 0,
			'IsTaxable' => 0,
			'Desc' => 31,
			'ItemPurchaseTaxRef ListID' => 0,
			'ItemPurchaseTaxRef FullName' => 31,
			'ItemSalesTaxRef ListID' => 0,
			'ItemSalesTaxRef FullName' => 31,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'Name' => 999.99,
			'IsActive' => 999.99,
			'IsTaxable' => 999.99,
			'Desc' => 999.99,
			'ItemPurchaseTaxRef ListID' => 999.99,
			'ItemPurchaseTaxRef FullName' => 999.99,
			'ItemSalesTaxRef ListID' => 999.99,
			'ItemSalesTaxRef FullName' => 999.99,
			'IncludeRetElement' => 4.0,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'Name' => false,
			'IsActive' => false,
			'IsTaxable' => false,
			'Desc' => false,
			'ItemPurchaseTaxRef ListID' => false,
			'ItemPurchaseTaxRef FullName' => false,
			'ItemSalesTaxRef ListID' => false,
			'ItemSalesTaxRef FullName' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'Name',
			'IsActive',
			'IsTaxable',
			'Desc',
			'ItemPurchaseTaxRef',
			'ItemPurchaseTaxRef ListID',
			'ItemPurchaseTaxRef FullName',
			'ItemSalesTaxRef',
			'ItemSalesTaxRef ListID',
			'ItemSalesTaxRef FullName',
			'IncludeRetElement',
		];

		return $paths;
	}
}
