<?php declare(strict_types=1);

/**
 * Schema object for: TimeTrackingAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class TimeTrackingAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'TimeTrackingAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TxnDate' => 'DATETYPE',
		'EntityRef ListID' => 'IDTYPE',
		'EntityRef FullName' => 'STRTYPE',
		'CustomerRef ListID' => 'IDTYPE',
		'CustomerRef FullName' => 'STRTYPE',
		'ItemServiceRef ListID' => 'IDTYPE',
		'ItemServiceRef FullName' => 'STRTYPE',
		'Rate' => 'PRICETYPE',
		'Duration' => 'TIMEINTERVALTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'PayrollItemWageRef ListID' => 'IDTYPE',
		'PayrollItemWageRef FullName' => 'STRTYPE',
		'Notes' => 'STRTYPE',
		'BillableStatus' => 'ENUMTYPE',
		'ExternalGUID' => 'GUIDTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'EntityRef FullName' => 209,
		'CustomerRef FullName' => 209,
		'ItemServiceRef FullName' => 159,
		'ClassRef FullName' => 159,
		'PayrollItemWageRef FullName' => 31,
		'Notes' => 4095,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'BillableStatus' => 6.0,
		'ExternalGUID' => 9.0,
		'IncludeRetElement' => 4.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
		'Rate' => ['US','CA','UK','AU'],
		'PayrollItemWageRef ListID' => ['OE'],
		'PayrollItemWageRef FullName' => ['OE'],
		'ExternalGUID' => ['OE'],
		'IncludeRetElement' => ['OE'],
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TxnDate',
		'EntityRef',
		'EntityRef ListID',
		'EntityRef FullName',
		'CustomerRef',
		'CustomerRef ListID',
		'CustomerRef FullName',
		'ItemServiceRef',
		'ItemServiceRef ListID',
		'ItemServiceRef FullName',
		'Rate',
		'Duration',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'PayrollItemWageRef',
		'PayrollItemWageRef ListID',
		'PayrollItemWageRef FullName',
		'Notes',
		'BillableStatus',
		'ExternalGUID',
		'IncludeRetElement',
	];
}
