<?php declare(strict_types=1);

/**
 * Schema object for: ToDoModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class ToDoModRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'ToDoMod ListID' => 'IDTYPE',
			'ToDoMod EditSequence' => 'STRTYPE',
			'ToDoMod Notes' => 'STRTYPE',
			'ToDoMod IsActive' => 'BOOLTYPE',
			'ToDoMod Type' => 'ENUMTYPE',
			'ToDoMod Priority' => 'ENUMTYPE',
			'ToDoMod CustomerRef ListID' => 'IDTYPE',
			'ToDoMod CustomerRef FullName' => 'STRTYPE',
			'ToDoMod EmployeeRef ListID' => 'IDTYPE',
			'ToDoMod EmployeeRef FullName' => 'STRTYPE',
			'ToDoMod LeadRef ListID' => 'IDTYPE',
			'ToDoMod LeadRef FullName' => 'STRTYPE',
			'ToDoMod VendorRef ListID' => 'IDTYPE',
			'ToDoMod VendorRef FullName' => 'STRTYPE',
			'ToDoMod IsDone' => 'BOOLTYPE',
			'ToDoMod ReminderDate' => 'DATETYPE',
			'ToDoMod ReminderTime' => 'TIMEINTERVALTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'ToDoMod ListID' => 0,
			'ToDoMod EditSequence' => 16,
			'ToDoMod Notes' => 4095,
			'ToDoMod IsActive' => 0,
			'ToDoMod Type' => 0,
			'ToDoMod Priority' => 0,
			'ToDoMod CustomerRef ListID' => 0,
			'ToDoMod CustomerRef FullName' => 209,
			'ToDoMod EmployeeRef ListID' => 0,
			'ToDoMod EmployeeRef FullName' => 209,
			'ToDoMod LeadRef ListID' => 0,
			'ToDoMod LeadRef FullName' => 209,
			'ToDoMod VendorRef ListID' => 0,
			'ToDoMod VendorRef FullName' => 209,
			'ToDoMod IsDone' => 0,
			'ToDoMod ReminderDate' => 0,
			'ToDoMod ReminderTime' => 0,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'ToDoMod ListID' => 999.99,
			'ToDoMod EditSequence' => 999.99,
			'ToDoMod Notes' => 999.99,
			'ToDoMod IsActive' => 999.99,
			'ToDoMod Type' => 13.0,
			'ToDoMod Priority' => 13.0,
			'ToDoMod CustomerRef ListID' => 999.99,
			'ToDoMod CustomerRef FullName' => 999.99,
			'ToDoMod EmployeeRef ListID' => 999.99,
			'ToDoMod EmployeeRef FullName' => 999.99,
			'ToDoMod LeadRef ListID' => 999.99,
			'ToDoMod LeadRef FullName' => 999.99,
			'ToDoMod VendorRef ListID' => 999.99,
			'ToDoMod VendorRef FullName' => 999.99,
			'ToDoMod IsDone' => 999.99,
			'ToDoMod ReminderDate' => 999.99,
			'ToDoMod ReminderTime' => 13.0,
			'IncludeRetElement' => 4.0,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'ToDoMod ListID' => false,
			'ToDoMod EditSequence' => false,
			'ToDoMod Notes' => false,
			'ToDoMod IsActive' => false,
			'ToDoMod Type' => false,
			'ToDoMod Priority' => false,
			'ToDoMod CustomerRef ListID' => false,
			'ToDoMod CustomerRef FullName' => false,
			'ToDoMod EmployeeRef ListID' => false,
			'ToDoMod EmployeeRef FullName' => false,
			'ToDoMod LeadRef ListID' => false,
			'ToDoMod LeadRef FullName' => false,
			'ToDoMod VendorRef ListID' => false,
			'ToDoMod VendorRef FullName' => false,
			'ToDoMod IsDone' => false,
			'ToDoMod ReminderDate' => false,
			'ToDoMod ReminderTime' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'ToDoMod',
			'ToDoMod ListID',
			'ToDoMod EditSequence',
			'ToDoMod Notes',
			'ToDoMod IsActive',
			'ToDoMod Type',
			'ToDoMod Priority',
			'ToDoMod CustomerRef ListID',
			'ToDoMod CustomerRef FullName',
			'ToDoMod EmployeeRef ListID',
			'ToDoMod EmployeeRef FullName',
			'ToDoMod LeadRef ListID',
			'ToDoMod LeadRef FullName',
			'ToDoMod VendorRef ListID',
			'ToDoMod VendorRef FullName',
			'ToDoMod IsDone',
			'ToDoMod ReminderDate',
			'ToDoMod ReminderTime',
			'IncludeRetElement',
		];

		return $paths;
	}
}
