<?php declare(strict_types=1);

/**
 * Schema object for: TransferSlipQueryRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbposxmlops30.xml file in this package.
 */
final class TransferSlipQueryRq extends AbstractSchemaObject
{
	/**
	 * This QuickBooks Action is found only in the QuickBooks Point of Sale (QBPOS) sdk.
	 * @var bool
	 */
	protected $_isQbxmlPosOnly = true;

	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'MaxReturned' => 'INTTYPE',
		'OwnerID' => 'GUIDTYPE',
		'TxnID' => 'IDTYPE',
		'TimeCreatedFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TimeCreatedFilter TimeCreated' => 'DATETIMETYPE',
		'TimeCreatedRangeFilter FromTimeCreated' => 'DATETIMETYPE',
		'TimeCreatedRangeFilter ToTimeCreated' => 'DATETIMETYPE',
		'TimeModifiedFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TimeModifiedFilter TimeModified' => 'DATETIMETYPE',
		'TimeModifiedRangeFilter FromTimeModified' => 'DATETIMETYPE',
		'TimeModifiedRangeFilter ToTimeModified' => 'DATETIMETYPE',
		'AssociateFilter MatchStringCriterion' => 'ENUMTYPE',
		'AssociateFilter Associate' => 'STRTYPE',
		'AssociateRangeFilter FromAssociate' => 'STRTYPE',
		'AssociateRangeFilter ToAssociate' => 'STRTYPE',
		'CarrierFilter MatchStringCriterion' => 'ENUMTYPE',
		'CarrierFilter Carrier' => 'STRTYPE',
		'CarrierRangeFilter FromCarrier' => 'STRTYPE',
		'CarrierRangeFilter ToCarrier' => 'STRTYPE',
		'CommentsFilter MatchStringCriterion' => 'ENUMTYPE',
		'CommentsFilter Comments' => 'STRTYPE',
		'CommentsRangeFilter FromComments' => 'STRTYPE',
		'CommentsRangeFilter ToComments' => 'STRTYPE',
		'FreightFilter MatchNumericCriterion' => 'ENUMTYPE',
		'FreightFilter Freight' => 'AMTTYPE',
		'FreightRangeFilter FromFreight' => 'AMTTYPE',
		'FreightRangeFilter ToFreight' => 'AMTTYPE',
		'FromStoreNumberFilter MatchNumericCriterion' => 'ENUMTYPE',
		'FromStoreNumberFilter FromStoreNumber' => 'INTTYPE',
		'FromStoreNumberRangeFilter FromFromStoreNumber' => 'INTTYPE',
		'FromStoreNumberRangeFilter ToFromStoreNumber' => 'INTTYPE',
		'HistoryDocStatus' => 'ENUMTYPE',
		'ItemsCountFilter MatchNumericCriterion' => 'ENUMTYPE',
		'ItemsCountFilter ItemsCount' => 'INTTYPE',
		'ItemsCountRangeFilter FromItemsCount' => 'INTTYPE',
		'ItemsCountRangeFilter ToItemsCount' => 'INTTYPE',
		'QuickBooksFlag' => 'ENUMTYPE',
		'SlipETAFilter MatchNumericCriterion' => 'ENUMTYPE',
		'SlipETAFilter SlipETA' => 'DATETYPE',
		'SlipETARangeFilter FromSlipETA' => 'DATETYPE',
		'SlipETARangeFilter ToSlipETA' => 'DATETYPE',
		'SlipNumberFilter MatchNumericCriterion' => 'ENUMTYPE',
		'SlipNumberFilter SlipNumber' => 'INTTYPE',
		'SlipNumberRangeFilter FromSlipNumber' => 'INTTYPE',
		'SlipNumberRangeFilter ToSlipNumber' => 'INTTYPE',
		'StoreExchangeStatus' => 'ENUMTYPE',
		'ToStoreNumberFilter MatchNumericCriterion' => 'ENUMTYPE',
		'ToStoreNumberFilter ToStoreNumber' => 'INTTYPE',
		'ToStoreNumberRangeFilter FromToStoreNumber' => 'INTTYPE',
		'ToStoreNumberRangeFilter ToToStoreNumber' => 'INTTYPE',
		'TotalCostFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TotalCostFilter TotalCost' => 'AMTTYPE',
		'TotalCostRangeFilter FromTotalCost' => 'AMTTYPE',
		'TotalCostRangeFilter ToTotalCost' => 'AMTTYPE',
		'TotalQtyFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TotalQtyFilter TotalQty' => 'QUANTYPE',
		'TotalQtyRangeFilter FromTotalQty' => 'QUANTYPE',
		'TotalQtyRangeFilter ToTotalQty' => 'QUANTYPE',
		'TxnDateFilter MatchNumericCriterion' => 'ENUMTYPE',
		'TxnDateFilter TxnDate' => 'DATETYPE',
		'TxnDateRangeFilter FromTxnDate' => 'DATETYPE',
		'TxnDateRangeFilter ToTxnDate' => 'DATETYPE',
		'TxnState' => 'ENUMTYPE',
		'WorkstationFilter MatchNumericCriterion' => 'ENUMTYPE',
		'WorkstationFilter Workstation' => 'INTTYPE',
		'WorkstationRangeFilter FromWorkstation' => 'INTTYPE',
		'WorkstationRangeFilter ToWorkstation' => 'INTTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'AssociateFilter Associate' => 40,
		'AssociateRangeFilter FromAssociate' => 40,
		'AssociateRangeFilter ToAssociate' => 40,
		'CarrierFilter Carrier' => 15,
		'CarrierRangeFilter FromCarrier' => 15,
		'CarrierRangeFilter ToCarrier' => 15,
		'CommentsFilter Comments' => 300,
		'CommentsRangeFilter FromComments' => 300,
		'CommentsRangeFilter ToComments' => 300,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'TxnState' => 1.1,
		'IncludeRetElement' => 2.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'OwnerID' => true,
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'MaxReturned',
		'OwnerID',
		'TxnID',
		'TimeCreatedFilter',
		'TimeCreatedFilter MatchNumericCriterion',
		'TimeCreatedFilter TimeCreated',
		'TimeCreatedRangeFilter',
		'TimeCreatedRangeFilter FromTimeCreated',
		'TimeCreatedRangeFilter ToTimeCreated',
		'TimeModifiedFilter',
		'TimeModifiedFilter MatchNumericCriterion',
		'TimeModifiedFilter TimeModified',
		'TimeModifiedRangeFilter',
		'TimeModifiedRangeFilter FromTimeModified',
		'TimeModifiedRangeFilter ToTimeModified',
		'AssociateFilter',
		'AssociateFilter MatchStringCriterion',
		'AssociateFilter Associate',
		'AssociateRangeFilter',
		'AssociateRangeFilter FromAssociate',
		'AssociateRangeFilter ToAssociate',
		'CarrierFilter',
		'CarrierFilter MatchStringCriterion',
		'CarrierFilter Carrier',
		'CarrierRangeFilter',
		'CarrierRangeFilter FromCarrier',
		'CarrierRangeFilter ToCarrier',
		'CommentsFilter',
		'CommentsFilter MatchStringCriterion',
		'CommentsFilter Comments',
		'CommentsRangeFilter',
		'CommentsRangeFilter FromComments',
		'CommentsRangeFilter ToComments',
		'FreightFilter',
		'FreightFilter MatchNumericCriterion',
		'FreightFilter Freight',
		'FreightRangeFilter',
		'FreightRangeFilter FromFreight',
		'FreightRangeFilter ToFreight',
		'FromStoreNumberFilter',
		'FromStoreNumberFilter MatchNumericCriterion',
		'FromStoreNumberFilter FromStoreNumber',
		'FromStoreNumberRangeFilter',
		'FromStoreNumberRangeFilter FromFromStoreNumber',
		'FromStoreNumberRangeFilter ToFromStoreNumber',
		'HistoryDocStatus',
		'ItemsCountFilter',
		'ItemsCountFilter MatchNumericCriterion',
		'ItemsCountFilter ItemsCount',
		'ItemsCountRangeFilter',
		'ItemsCountRangeFilter FromItemsCount',
		'ItemsCountRangeFilter ToItemsCount',
		'QuickBooksFlag',
		'SlipETAFilter',
		'SlipETAFilter MatchNumericCriterion',
		'SlipETAFilter SlipETA',
		'SlipETARangeFilter',
		'SlipETARangeFilter FromSlipETA',
		'SlipETARangeFilter ToSlipETA',
		'SlipNumberFilter',
		'SlipNumberFilter MatchNumericCriterion',
		'SlipNumberFilter SlipNumber',
		'SlipNumberRangeFilter',
		'SlipNumberRangeFilter FromSlipNumber',
		'SlipNumberRangeFilter ToSlipNumber',
		'StoreExchangeStatus',
		'ToStoreNumberFilter',
		'ToStoreNumberFilter MatchNumericCriterion',
		'ToStoreNumberFilter ToStoreNumber',
		'ToStoreNumberRangeFilter',
		'ToStoreNumberRangeFilter FromToStoreNumber',
		'ToStoreNumberRangeFilter ToToStoreNumber',
		'TotalCostFilter',
		'TotalCostFilter MatchNumericCriterion',
		'TotalCostFilter TotalCost',
		'TotalCostRangeFilter',
		'TotalCostRangeFilter FromTotalCost',
		'TotalCostRangeFilter ToTotalCost',
		'TotalQtyFilter',
		'TotalQtyFilter MatchNumericCriterion',
		'TotalQtyFilter TotalQty',
		'TotalQtyRangeFilter',
		'TotalQtyRangeFilter FromTotalQty',
		'TotalQtyRangeFilter ToTotalQty',
		'TxnDateFilter',
		'TxnDateFilter MatchNumericCriterion',
		'TxnDateFilter TxnDate',
		'TxnDateRangeFilter',
		'TxnDateRangeFilter FromTxnDate',
		'TxnDateRangeFilter ToTxnDate',
		'TxnState',
		'WorkstationFilter',
		'WorkstationFilter MatchNumericCriterion',
		'WorkstationFilter Workstation',
		'WorkstationRangeFilter',
		'WorkstationRangeFilter FromWorkstation',
		'WorkstationRangeFilter ToWorkstation',
		'IncludeRetElement',
	];
}
