<?php declare(strict_types=1);

/**
 * Schema object for: TransferModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class TransferModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TransferMod TxnID' => 'IDTYPE',
		'TransferMod EditSequence' => 'STRTYPE',
		'TransferMod TxnDate' => 'DATETYPE',
		'TransferMod TransferFromAccountRef ListID' => 'IDTYPE',
		'TransferMod TransferFromAccountRef FullName' => 'STRTYPE',
		'TransferMod TransferToAccountRef ListID' => 'IDTYPE',
		'TransferMod TransferToAccountRef FullName' => 'STRTYPE',
		'TransferMod ClassRef ListID' => 'IDTYPE',
		'TransferMod ClassRef FullName' => 'STRTYPE',
		'TransferMod Amount' => 'AMTTYPE',
		'TransferMod Memo' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'TransferMod EditSequence' => 16,
		'TransferMod TransferFromAccountRef FullName' => 159,
		'TransferMod TransferToAccountRef FullName' => 159,
		'TransferMod ClassRef FullName' => 159,
		'TransferMod Memo' => 4095,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TransferMod',
		'TransferMod TxnID',
		'TransferMod EditSequence',
		'TransferMod TxnDate',
		'TransferMod TransferFromAccountRef ListID',
		'TransferMod TransferFromAccountRef FullName',
		'TransferMod TransferToAccountRef ListID',
		'TransferMod TransferToAccountRef FullName',
		'TransferMod ClassRef ListID',
		'TransferMod ClassRef FullName',
		'TransferMod Amount',
		'TransferMod Memo',
		'IncludeRetElement',
	];
}
