<?php declare(strict_types=1);

/**
 * Schema object for: TransferInventoryModRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class TransferInventoryModRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'TransferInventoryMod TxnID' => 'IDTYPE',
		'TransferInventoryMod EditSequence' => 'STRTYPE',
		'TransferInventoryMod TxnDate' => 'DATETYPE',
		'TransferInventoryMod RefNumber' => 'STRTYPE',
		'TransferInventoryMod FromInventorySiteRef ListID' => 'IDTYPE',
		'TransferInventoryMod FromInventorySiteRef FullName' => 'STRTYPE',
		'TransferInventoryMod ToInventorySiteRef ListID' => 'IDTYPE',
		'TransferInventoryMod ToInventorySiteRef FullName' => 'STRTYPE',
		'TransferInventoryMod Memo' => 'STRTYPE',
		'TransferInventoryMod TransferInventoryLineMod TxnLineID' => 'IDTYPE',
		'TransferInventoryMod TransferInventoryLineMod ItemRef ListID' => 'IDTYPE',
		'TransferInventoryMod TransferInventoryLineMod ItemRef FullName' => 'STRTYPE',
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef ListID' => 'IDTYPE',
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef FullName' => 'STRTYPE',
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef ListID' => 'IDTYPE',
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef FullName' => 'STRTYPE',
		'TransferInventoryMod TransferInventoryLineMod QuantityToTransfer' => 'QUANTYPE',
		'TransferInventoryMod TransferInventoryLineMod SerialNumber' => 'STRTYPE',
		'TransferInventoryMod TransferInventoryLineMod LotNumber' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'TransferInventoryMod EditSequence' => 16,
		'TransferInventoryMod RefNumber' => 11,
		'TransferInventoryMod FromInventorySiteRef FullName' => 31,
		'TransferInventoryMod ToInventorySiteRef FullName' => 31,
		'TransferInventoryMod Memo' => 4095,
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef FullName' => 31,
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef FullName' => 31,
		'TransferInventoryMod TransferInventoryLineMod SerialNumber' => 4095,
		'TransferInventoryMod TransferInventoryLineMod LotNumber' => 40,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef ListID' => 12.0,
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef FullName' => 12.0,
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef ListID' => 12.0,
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef FullName' => 12.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'TransferInventoryMod',
		'TransferInventoryMod TxnID',
		'TransferInventoryMod EditSequence',
		'TransferInventoryMod TxnDate',
		'TransferInventoryMod RefNumber',
		'TransferInventoryMod FromInventorySiteRef ListID',
		'TransferInventoryMod FromInventorySiteRef FullName',
		'TransferInventoryMod ToInventorySiteRef ListID',
		'TransferInventoryMod ToInventorySiteRef FullName',
		'TransferInventoryMod Memo',
		'TransferInventoryMod TransferInventoryLineMod TxnLineID',
		'TransferInventoryMod TransferInventoryLineMod ItemRef ListID',
		'TransferInventoryMod TransferInventoryLineMod ItemRef FullName',
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef ListID',
		'TransferInventoryMod TransferInventoryLineMod FromInventorySiteLocationRef FullName',
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef ListID',
		'TransferInventoryMod TransferInventoryLineMod ToInventorySiteLocationRef FullName',
		'TransferInventoryMod TransferInventoryLineMod QuantityToTransfer',
		'TransferInventoryMod TransferInventoryLineMod SerialNumber',
		'TransferInventoryMod TransferInventoryLineMod LotNumber',
		'IncludeRetElement',
	];
}
