<?php declare(strict_types=1);

/**
 * Schema object for: TransferAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class TransferAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = '';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'TransferAdd TxnDate' => 'DATETYPE',
			'TransferAdd TransferFromAccountRef ListID' => 'IDTYPE',
			'TransferAdd TransferFromAccountRef FullName' => 'STRTYPE',
			'TransferAdd TransferToAccountRef ListID' => 'IDTYPE',
			'TransferAdd TransferToAccountRef FullName' => 'STRTYPE',
			'TransferAdd ClassRef ListID' => 'IDTYPE',
			'TransferAdd ClassRef FullName' => 'STRTYPE',
			'TransferAdd Amount' => 'AMTTYPE',
			'TransferAdd Memo' => 'STRTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'TransferAdd TxnDate' => 0,
			'TransferAdd TransferFromAccountRef ListID' => 0,
			'TransferAdd TransferFromAccountRef FullName' => 159,
			'TransferAdd TransferToAccountRef ListID' => 0,
			'TransferAdd TransferToAccountRef FullName' => 159,
			'TransferAdd ClassRef ListID' => 0,
			'TransferAdd ClassRef FullName' => 159,
			'TransferAdd Amount' => 0,
			'TransferAdd Memo' => 4095,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'TransferAdd TxnDate' => 999.99,
			'TransferAdd TransferFromAccountRef ListID' => 999.99,
			'TransferAdd TransferFromAccountRef FullName' => 999.99,
			'TransferAdd TransferToAccountRef ListID' => 999.99,
			'TransferAdd TransferToAccountRef FullName' => 999.99,
			'TransferAdd ClassRef ListID' => 999.99,
			'TransferAdd ClassRef FullName' => 999.99,
			'TransferAdd Amount' => 999.99,
			'TransferAdd Memo' => 999.99,
			'IncludeRetElement' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'TransferAdd TxnDate' => false,
			'TransferAdd TransferFromAccountRef ListID' => false,
			'TransferAdd TransferFromAccountRef FullName' => false,
			'TransferAdd TransferToAccountRef ListID' => false,
			'TransferAdd TransferToAccountRef FullName' => false,
			'TransferAdd ClassRef ListID' => false,
			'TransferAdd ClassRef FullName' => false,
			'TransferAdd Amount' => false,
			'TransferAdd Memo' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'TransferAdd',
			'TransferAdd TxnDate',
			'TransferAdd TransferFromAccountRef ListID',
			'TransferAdd TransferFromAccountRef FullName',
			'TransferAdd TransferToAccountRef ListID',
			'TransferAdd TransferToAccountRef FullName',
			'TransferAdd ClassRef ListID',
			'TransferAdd ClassRef FullName',
			'TransferAdd Amount',
			'TransferAdd Memo',
			'IncludeRetElement',
		];

		return $paths;
	}
}
