<?php declare(strict_types=1);

/**
 * Schema object for: UIExtensionSubscriptionAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class UIExtensionSubscriptionAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'UIExtensionSubscriptionAdd SubscriberID' => 'GUIDTYPE',
		'UIExtensionSubscriptionAdd COMCallbackInfo AppName' => 'STRTYPE',
		'UIExtensionSubscriptionAdd COMCallbackInfo ProgID' => 'STRTYPE',
		'UIExtensionSubscriptionAdd COMCallbackInfo CLSID' => 'GUIDTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription AddToMenu' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition VisibleIf' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition VisibleIfNot' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition EnabledIf' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition EnabledIfNot' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem MenuText' => 'STRTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem EventTag' => 'STRTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition VisibleIf' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition VisibleIfNot' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition EnabledIf' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition EnabledIfNot' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem MenuText' => 'STRTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem EventTag' => 'STRTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition VisibleIf' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition VisibleIfNot' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition EnabledIf' => 'ENUMTYPE',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition EnabledIfNot' => 'ENUMTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'UIExtensionSubscriptionAdd COMCallbackInfo AppName' => 128,
		'UIExtensionSubscriptionAdd COMCallbackInfo ProgID' => 128,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem MenuText' => 50,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem EventTag' => 50,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem MenuText' => 50,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem EventTag' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition VisibleIf' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition VisibleIfNot' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition EnabledIf' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition EnabledIfNot' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition VisibleIf' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition VisibleIfNot' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition EnabledIf' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition EnabledIfNot' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition VisibleIf' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition VisibleIfNot' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition EnabledIf' => true,
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition EnabledIfNot' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'UIExtensionSubscriptionAdd',
		'UIExtensionSubscriptionAdd SubscriberID',
		'UIExtensionSubscriptionAdd COMCallbackInfo AppName',
		'UIExtensionSubscriptionAdd COMCallbackInfo ProgID',
		'UIExtensionSubscriptionAdd COMCallbackInfo CLSID',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription AddToMenu',
		'UIExtensionSubscriptionAdd',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition VisibleIf',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition VisibleIfNot',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition EnabledIf',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu DisplayCondition EnabledIfNot',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem MenuText',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem EventTag',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition VisibleIf',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition VisibleIfNot',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition EnabledIf',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription Submenu MenuItem DisplayCondition EnabledIfNot',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem MenuText',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem EventTag',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition VisibleIf',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition VisibleIfNot',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition EnabledIf',
		'UIExtensionSubscriptionAdd MenuExtensionSubscription MenuItem DisplayCondition EnabledIfNot',
	];
}
