<?php declare(strict_types=1);

/**
 * Schema object for: UnitOfMeasureSetAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class UnitOfMeasureSetAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = 'UnitOfMeasureSetAdd';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'Name' => 'STRTYPE',
			'IsActive' => 'BOOLTYPE',
			'UnitOfMeasureType' => 'ENUMTYPE',
			'BaseUnit Name' => 'STRTYPE',
			'BaseUnit Abbreviation' => 'STRTYPE',
			'RelatedUnit Name' => 'STRTYPE',
			'RelatedUnit Abbreviation' => 'STRTYPE',
			'RelatedUnit ConversionRatio' => 'PRICETYPE',
			'DefaultUnit UnitUsedFor' => 'ENUMTYPE',
			'DefaultUnit Unit' => 'STRTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'Name' => 31,
			'IsActive' => 0,
			'UnitOfMeasureType' => 0,
			'BaseUnit Name' => 31,
			'BaseUnit Abbreviation' => 31,
			'RelatedUnit Name' => 31,
			'RelatedUnit Abbreviation' => 31,
			'RelatedUnit ConversionRatio' => 0,
			'DefaultUnit UnitUsedFor' => 0,
			'DefaultUnit Unit' => 31,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'Name' => 999.99,
			'IsActive' => 999.99,
			'UnitOfMeasureType' => 999.99,
			'BaseUnit Name' => 999.99,
			'BaseUnit Abbreviation' => 999.99,
			'RelatedUnit Name' => 999.99,
			'RelatedUnit Abbreviation' => 999.99,
			'RelatedUnit ConversionRatio' => 999.99,
			'DefaultUnit UnitUsedFor' => 999.99,
			'DefaultUnit Unit' => 999.99,
			'IncludeRetElement' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'Name' => false,
			'IsActive' => false,
			'UnitOfMeasureType' => false,
			'BaseUnit Name' => false,
			'BaseUnit Abbreviation' => false,
			'RelatedUnit Name' => false,
			'RelatedUnit Abbreviation' => false,
			'RelatedUnit ConversionRatio' => false,
			'DefaultUnit UnitUsedFor' => false,
			'DefaultUnit Unit' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'Name',
			'IsActive',
			'UnitOfMeasureType',
			'BaseUnit',
			'BaseUnit Name',
			'BaseUnit Abbreviation',
			'RelatedUnit',
			'RelatedUnit Name',
			'RelatedUnit Abbreviation',
			'RelatedUnit ConversionRatio',
			'DefaultUnit',
			'DefaultUnit UnitUsedFor',
			'DefaultUnit Unit',
			'IncludeRetElement',
		];

		return $paths;
	}
}
