<?php declare(strict_types=1);

/**
 * Schema object for: VehicleMileageAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!  This file is auto-generated by QBXML\Schema\Generator and the data/qbxmlops130.xml schema
 */
class VehicleMileageAddRq extends AbstractSchemaObject
{
	protected function &_qbxmlWrapper(): string
	{
		static $wrapper = 'VehicleMileageAdd';

		return $wrapper;
	}

	protected function &_dataTypePaths(): array
	{
		static $paths = [
			'VehicleRef ListID' => 'IDTYPE',
			'VehicleRef FullName' => 'STRTYPE',
			'CustomerRef ListID' => 'IDTYPE',
			'CustomerRef FullName' => 'STRTYPE',
			'ItemRef ListID' => 'IDTYPE',
			'ItemRef FullName' => 'STRTYPE',
			'ClassRef ListID' => 'IDTYPE',
			'ClassRef FullName' => 'STRTYPE',
			'TripStartDate' => 'DATETYPE',
			'TripEndDate' => 'DATETYPE',
			'OdometerStart' => 'QUANTYPE',
			'OdometerEnd' => 'QUANTYPE',
			'TotalMiles' => 'QUANTYPE',
			'Notes' => 'STRTYPE',
			'BillableStatus' => 'ENUMTYPE',
			'IncludeRetElement' => 'STRTYPE',
		];

		return $paths;
	}

	protected function &_maxLengthPaths(): array
	{
		static $paths = [
			'VehicleRef ListID' => 0,
			'VehicleRef FullName' => 31,
			'CustomerRef ListID' => 0,
			'CustomerRef FullName' => 31,
			'ItemRef ListID' => 0,
			'ItemRef FullName' => 31,
			'ClassRef ListID' => 0,
			'ClassRef FullName' => 31,
			'TripStartDate' => 0,
			'TripEndDate' => 0,
			'OdometerStart' => 0,
			'OdometerEnd' => 0,
			'TotalMiles' => 0,
			'Notes' => 4095,
			'BillableStatus' => 0,
			'IncludeRetElement' => 50,
		];

		return $paths;
	}

	protected function &_isOptionalPaths(): array
	{
		// This seems broken when a parent is optional but an element is required if the parent is included (See HostQueryRq IncludeMaxCapacity).
		static $paths = []; //'_isOptionalPaths ';

		return $paths;
	}

	protected function &_sinceVersionPaths(): array
	{
		static $paths = [
			'VehicleRef ListID' => 999.99,
			'VehicleRef FullName' => 999.99,
			'CustomerRef ListID' => 999.99,
			'CustomerRef FullName' => 999.99,
			'ItemRef ListID' => 999.99,
			'ItemRef FullName' => 999.99,
			'ClassRef ListID' => 999.99,
			'ClassRef FullName' => 999.99,
			'TripStartDate' => 999.99,
			'TripEndDate' => 999.99,
			'OdometerStart' => 999.99,
			'OdometerEnd' => 999.99,
			'TotalMiles' => 999.99,
			'Notes' => 999.99,
			'BillableStatus' => 999.99,
			'IncludeRetElement' => 999.99,
		];

		return $paths;
	}

	protected function &_isRepeatablePaths(): array
	{
		static $paths = [
			'VehicleRef ListID' => false,
			'VehicleRef FullName' => false,
			'CustomerRef ListID' => false,
			'CustomerRef FullName' => false,
			'ItemRef ListID' => false,
			'ItemRef FullName' => false,
			'ClassRef ListID' => false,
			'ClassRef FullName' => false,
			'TripStartDate' => false,
			'TripEndDate' => false,
			'OdometerStart' => false,
			'OdometerEnd' => false,
			'TotalMiles' => false,
			'Notes' => false,
			'BillableStatus' => false,
			'IncludeRetElement' => true,
		];

		return $paths;
	}

	/*
	protected function &_inLocalePaths(): array
	{
		static $paths = [
			'FirstName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
			'LastName' => ['QBD', 'QBCA', 'QBUK', 'QBAU'],
		];

		return $paths;
	}
	*/

	protected function &_reorderPathsPaths(): array
	{
		static $paths = [
			'VehicleRef',
			'VehicleRef ListID',
			'VehicleRef FullName',
			'CustomerRef',
			'CustomerRef ListID',
			'CustomerRef FullName',
			'ItemRef',
			'ItemRef ListID',
			'ItemRef FullName',
			'ClassRef',
			'ClassRef ListID',
			'ClassRef FullName',
			'TripStartDate',
			'TripEndDate',
			'OdometerStart',
			'OdometerEnd',
			'TotalMiles',
			'Notes',
			'BillableStatus',
			'IncludeRetElement',
		];

		return $paths;
	}
}
