<?php declare(strict_types=1);

/**
 * Schema object for: VehicleMileageAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbxmlops130.xml file in this package.
 */
final class VehicleMileageAddRq extends AbstractSchemaObject
{
	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = 'VehicleMileageAdd';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'VehicleRef ListID' => 'IDTYPE',
		'VehicleRef FullName' => 'STRTYPE',
		'CustomerRef ListID' => 'IDTYPE',
		'CustomerRef FullName' => 'STRTYPE',
		'ItemRef ListID' => 'IDTYPE',
		'ItemRef FullName' => 'STRTYPE',
		'ClassRef ListID' => 'IDTYPE',
		'ClassRef FullName' => 'STRTYPE',
		'TripStartDate' => 'DATETYPE',
		'TripEndDate' => 'DATETYPE',
		'OdometerStart' => 'QUANTYPE',
		'OdometerEnd' => 'QUANTYPE',
		'TotalMiles' => 'QUANTYPE',
		'Notes' => 'STRTYPE',
		'BillableStatus' => 'ENUMTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'VehicleRef FullName' => 31,
		'CustomerRef FullName' => 209,
		'ClassRef FullName' => 159,
		'Notes' => 4095,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'VehicleRef',
		'VehicleRef ListID',
		'VehicleRef FullName',
		'CustomerRef',
		'CustomerRef ListID',
		'CustomerRef FullName',
		'ItemRef',
		'ItemRef ListID',
		'ItemRef FullName',
		'ClassRef',
		'ClassRef ListID',
		'ClassRef FullName',
		'TripStartDate',
		'TripEndDate',
		'OdometerStart',
		'OdometerEnd',
		'TotalMiles',
		'Notes',
		'BillableStatus',
		'IncludeRetElement',
	];
}
