<?php declare(strict_types=1);

/**
 * Schema object for: VoucherAddRq
 *
 * @author "Keith Palmer Jr." <Keith@ConsoliByte.com>
 * @license LICENSE.txt
 *
 * @package QuickBooks
 * @subpackage QBXML
 */

namespace QuickBooksPhpDevKit\QBXML\Schema\Object;

use QuickBooksPhpDevKit\QBXML\Schema\AbstractSchemaObject;

/**
 * WARNING!!!: This file is generated by QuickBooksPhpDevKit\QBXML\Schema\Generator using the /data/qbposxmlops30.xml file in this package.
 */
final class VoucherAddRq extends AbstractSchemaObject
{
	/**
	 * This QuickBooks Action is found only in the QuickBooks Point of Sale (QBPOS) sdk.
	 * @var bool
	 */
	protected $_isQbxmlPosOnly = true;

	/**
	 * Object's QBXML wrapping tag type
	 * @var string
	 */
	protected $_qbxmlWrapper = '';

	/**
	 * Field Datatype
	 * @var string[]
	 */
	protected $_dataTypePaths = [
		'VoucherAdd Associate' => 'STRTYPE',
		'VoucherAdd Comments' => 'STRTYPE',
		'VoucherAdd Discount' => 'AMTTYPE',
		'VoucherAdd DiscountPercent' => 'FLOATTYPE',
		'VoucherAdd Fee' => 'AMTTYPE',
		'VoucherAdd Freight' => 'AMTTYPE',
		'VoucherAdd InvoiceDate' => 'DATETYPE',
		'VoucherAdd InvoiceDueDate' => 'DATETYPE',
		'VoucherAdd InvoiceNumber' => 'STRTYPE',
		'VoucherAdd PayeeListID' => 'IDTYPE',
		'VoucherAdd PurchaseOrderTxnID' => 'IDTYPE',
		'VoucherAdd QuickBooksFlag' => 'ENUMTYPE',
		'VoucherAdd StoreNumber' => 'INTTYPE',
		'VoucherAdd TermsDiscount' => 'FLOATTYPE',
		'VoucherAdd TermsDiscountDays' => 'INTTYPE',
		'VoucherAdd TermsNetDays' => 'INTTYPE',
		'VoucherAdd TxnDate' => 'DATETYPE',
		'VoucherAdd TxnState' => 'ENUMTYPE',
		'VoucherAdd VendorListID' => 'IDTYPE',
		'VoucherAdd VoucherType' => 'ENUMTYPE',
		'VoucherAdd Workstation' => 'INTTYPE',
		'VoucherAdd VoucherItemAdd ListID' => 'IDTYPE',
		'VoucherAdd VoucherItemAdd ALU' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd Attribute' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd Cost' => 'AMTTYPE',
		'VoucherAdd VoucherItemAdd Desc1' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd Desc2' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd ExtendedCost' => 'AMTTYPE',
		'VoucherAdd VoucherItemAdd QtyReceived' => 'QUANTYPE',
		'VoucherAdd VoucherItemAdd SerialNumber' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd Size' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd UnitOfMeasure' => 'STRTYPE',
		'VoucherAdd VoucherItemAdd UPC' => 'STRTYPE',
		'IncludeRetElement' => 'STRTYPE',
	];

	/**
	 * Field Maximum Length
	 * @var int[]
	 */
	protected $_maxLengthPaths = [
		'VoucherAdd Associate' => 40,
		'VoucherAdd Comments' => 2000,
		'VoucherAdd InvoiceNumber' => 15,
		'VoucherAdd VoucherItemAdd ALU' => 20,
		'VoucherAdd VoucherItemAdd Attribute' => 12,
		'VoucherAdd VoucherItemAdd Desc1' => 30,
		'VoucherAdd VoucherItemAdd SerialNumber' => 25,
		'VoucherAdd VoucherItemAdd Size' => 12,
		'VoucherAdd VoucherItemAdd UnitOfMeasure' => 20,
		'VoucherAdd VoucherItemAdd UPC' => 18,
		'IncludeRetElement' => 50,
	];

	/**
	 * Field is optional (may be ommitted)
	 * @var bool[]
	 */
	protected $_isOptionalPaths = []; //'_isOptionalPaths ';

	/**
	 * Field Available Since QBXML Version #
	 * @var float[]
	 */
	protected $_sinceVersionPaths = [
		'VoucherAdd InvoiceDueDate' => 1.1,
		'VoucherAdd TermsDiscount' => 1.1,
		'VoucherAdd TermsDiscountDays' => 1.1,
		'VoucherAdd TermsNetDays' => 1.1,
		'VoucherAdd TxnState' => 1.1,
		'VoucherAdd VoucherItemAdd UnitOfMeasure' => 2.0,
		'IncludeRetElement' => 2.0,
	];

	/**
	 * Field May Be Included Multiple Times
	 * @var bool[]
	 */
	protected $_isRepeatablePaths = [
		'IncludeRetElement' => true,
	];

	/**
	 * Field Is Excluded From These Locales
	 *
	 * QuickBooks labels are QBD, QBCA, QBUK, QBAU, and QBOE but these are mapped to
	 * US, CA, UK, AU, and OE to match what is in the PackageInfo::Locale array.
	 * @var string[][]
	 */
	protected $_localeExcludedPaths = [
	];

	/**
	 * Fields In Order They Must Be Included In The QBXML Request
	 * @var string[]
	 */
	protected $_reorderPathsPaths = [
		'VoucherAdd',
		'VoucherAdd Associate',
		'VoucherAdd Comments',
		'VoucherAdd Discount',
		'VoucherAdd DiscountPercent',
		'VoucherAdd Fee',
		'VoucherAdd Freight',
		'VoucherAdd InvoiceDate',
		'VoucherAdd InvoiceDueDate',
		'VoucherAdd InvoiceNumber',
		'VoucherAdd PayeeListID',
		'VoucherAdd PurchaseOrderTxnID',
		'VoucherAdd QuickBooksFlag',
		'VoucherAdd StoreNumber',
		'VoucherAdd TermsDiscount',
		'VoucherAdd TermsDiscountDays',
		'VoucherAdd TermsNetDays',
		'VoucherAdd TxnDate',
		'VoucherAdd TxnState',
		'VoucherAdd VendorListID',
		'VoucherAdd VoucherType',
		'VoucherAdd Workstation',
		'VoucherAdd VoucherItemAdd ListID',
		'VoucherAdd VoucherItemAdd ALU',
		'VoucherAdd VoucherItemAdd Attribute',
		'VoucherAdd VoucherItemAdd Cost',
		'VoucherAdd VoucherItemAdd Desc1',
		'VoucherAdd VoucherItemAdd Desc2',
		'VoucherAdd VoucherItemAdd ExtendedCost',
		'VoucherAdd VoucherItemAdd QtyReceived',
		'VoucherAdd VoucherItemAdd SerialNumber',
		'VoucherAdd VoucherItemAdd Size',
		'VoucherAdd VoucherItemAdd UnitOfMeasure',
		'VoucherAdd VoucherItemAdd UPC',
		'IncludeRetElement',
	];
}
